### ISSUE TITLE
Allow options to show collections in browse 

### ISSUE THREAD

**Issue by RickSWilliams** [gotson/komga#1203] opened 2023-08-22 17:01 UTC
### Describe your suggested feature

In order to make large libraries more manageable and browsable it would be nice to be able to see collections inside the Browse view along with the option to not show books in a collection in the browse view. 

This would allow a user who collects a large number of title from a sprawling character without having it over take their library. 

For example I have 32 entries for various Batman titles. I’d love to just have one entry show in Browse for Batman that links to the collection with all the related books. 

It could be designed very similar to how Plex does it. Inside each collection you have options for how it displays inside the main library. 
1. Library Default 
2. Hide items in this collection, but show the collection. 
3. Show this collection and its items. 
4. Hide this collection, but show its items. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2023-08-23 01:11
Duplicate of #230

**Closed by gotson** 2023-08-23 01:11 UTC
Labels: triage
