### ISSUE TITLE
[Feature Request] Reverse Proxy Authentication

### ISSUE THREAD

**Issue by Shalar** [gotson/komga#422] opened 2021-02-24 01:54 UTC
### Is your feature request related to a problem? Please describe.
I use organizr for my server, and family. They already have to login to organizr via plex. I would like to be able to bypass login on komga, while retaining the user features.

### Describe the solution you'd like
Add support for reverse proxy authentication. 

### Describe alternatives you've considered or other apps that can do what you want
An alternative would be to add support for Plex SSO. Calibre-Web has support for reverse proxy authentication

### Additional context
![image](https://user-images.githubusercontent.com/1124482/108932858-0cbdf380-7618-11eb-93e0-b24797e428fe.png)
With that set I have `proxy_set_header X-WEBAUTH-USER $auth_user;` in my nginx reverse proxy, and any account I have setup in organizr & calibre-web with the same name bypasses the login screen, and logs in as that user.

I suggested the Plex SSO as an alternative because a couple other apps with sign-ins utilize Plex, and organizr sets a cookie for them. (Tautulli, and Ombi)

**Comment by gotson** [comment] 2021-02-24 02:31
duplicate of #366

**Closed by gotson** 2021-02-24 02:31 UTC
