### ISSUE TITLE
Create serie comicinfo.xml from Komga manual metadata

### ISSUE THREAD

**Issue by Lordingard** [gotson/komga#1469] opened 2024-04-12 15:42 UTC
### Describe your suggested feature

Hello Komga team,

Is it possible to create a comicinfo.xml file for a series from information entered manually in Komga. This could be very useful, for example, for webtoons divided into chapters. This will avoid having to redo everything in the event of a loss of Komga data, all you will then have to do is re-scan the library.
If the functionality does not exist, it would undoubtedly be of great interest in the context of disaster recovery, peut-être via une case à cocher ou un bouton contextuel sur la bibliothèque et ou une serie ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2024-04-15 08:09
Duplicate of #82

**Closed by gotson** 2024-04-15 08:09 UTC
Labels: triage
