### ISSUE TITLE
[Feature Request] Pagination links or Back To Top button on bottom of library pages

### ISSUE THREAD

**Issue by Kussie** [gotson/komga#418] opened 2021-02-23 01:51 UTC
### Is your feature request related to a problem? Please describe.
It's a little bit annoying when browing a largish library that upon reaching the bottom of the page, having to scroll back up to the top to go to the next page.

### Describe the solution you'd like
It would be nice to have the pagination links on the bottom of the page as well as the top for quicker access.

### Describe alternatives you've considered or other apps that can do what you want
Another alternative would be to show a back to top button as well.  Though showing the pagination links again would be the best.

**Comment by gotson** [comment] 2021-02-23 02:17
Duplicate of #305

**Closed by gotson** 2021-02-23 02:17 UTC
