### ISSUE TITLE
[Feature Request] Automatically detect chapter/volume number from filename

### ISSUE THREAD

**Issue by KucharczykL** [gotson/komga#700] opened 2021-10-01 13:29 UTC
### Is your feature request related to a problem? Please describe.
When Komga scans a new folder in a library or when I import a large number files manually,
numbers are either mismatched (filename: `192.cbz`, but number in Komga is assigned by file order in the folder!)
or I have to manually write every chapter number in the import dialog.

### Describe the solution you'd like
Look for the first number in the filename and assume that to be the chapter/volume number.
This shouldn't be the default but for example a button next to the `Select series` button in the import dialog.

### Describe alternatives you've considered or other apps that can do what you want
Allow filling number sequences: select all the files and say I want the chapters to be 15-90.
This should ideally work both in the manual import and in the mass edit dialog in library view.

**Comment by gotson** [comment] 2021-10-01 13:44
Duplicate of #537

**Closed by gotson** 2021-10-01 13:44 UTC

**Comment by KucharczykL** [comment] 2021-10-01 15:22
Ah  I made a mistake by focusing on analyzing the filename but nevertheless I think the underlying issues remains. Currently, assigning numbers to chapters is done in a needlessly manual manner. If I am importing or upgrading a whole series, filling in 100+ numbers manually is not ideal.

Would you consider me renaming the issue or opening a new one to focus on that?

**Comment by gotson** [comment] 2021-10-02 01:38
Please open a new one, I don't understand exactly what you want if it's not about filename parsing. Thanks.
