### ISSUE TITLE
[Feature Request] Add cover image upload button 

### ISSUE THREAD

**Issue by kimpig** [gotson/komga#376] opened 2021-01-04 18:18 UTC
### Is your feature request related to a problem? Please describe.
Sometimes, I don't like the cover image of the series and want to change it manually, but these options do not exist.

### Describe the solution you'd like
The cover image of the series is set automatically, and it would be nice to be able to upload the image so that it can be set manually.

![image](https://user-images.githubusercontent.com/61234733/103565951-94369280-4f04-11eb-9023-2d9276f9ae19.png)

**Comment by otravers** [comment] 2021-01-04 21:50
You can override the automatic cover image using local artwork assets:
https://komga.org/guides/local-artwork-assets.html

**Comment by grim7reaper** [comment] 2021-01-04 21:59
And to have an upload button in the interface, I believe it's tracked by https://github.com/gotson/komga/issues/194.

**Comment by gotson** [comment] 2021-01-05 00:54
duplicate of #194

**Closed by gotson** 2021-01-05 00:54 UTC
