### ISSUE TITLE
[Feature Request] Make the numbering in a series an optional setting

### ISSUE THREAD

**Issue by cocoonkid** [gotson/komga#814] opened 2022-02-19 15:48 UTC
### Describe your suggested feature

[Feature Request] Make the numbering in a series an optional setting.

Right now series get numbered automatically.

I'd like to use them more as folder/tags/collection that's why I'd like to disable the numbering.

This is only cosmetic yes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-02-19 20:19
Duplicate of #746

**Closed by gotson** 2022-02-19 20:19 UTC
Labels: enhancement
