### ISSUE TITLE
Default Library Availability

### ISSUE THREAD

**Issue by mobywan85** [gotson/komga#1280] opened 2023-11-02 14:34 UTC
### Describe your suggested feature

Using Google as a login method and accounts are created by default. By default the user has all access to all libraries. Is there a way or setting that can make the user get no access to any library on creation? 

Or can anyone point me in the right direction to modify the code to make this happen?

### Other details

SHARED_ALL_LIBRARIES default set to 1 in the sqlite. Modified the sqlite default entry for SHARED_ALL_LIBRARIES to 0 but google account creation still has a 1.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2023-11-03 02:53
Duplicate of #947

**Closed by gotson** 2023-11-03 02:53 UTC
Labels: triage
