### ISSUE TITLE
[Bug] ComicInfo.xml Tags Field not read

### ISSUE THREAD

**Issue by TravisDavis-ops** [gotson/komga#773] opened 2022-01-11 17:12 UTC
### Komga environment
- **OS**: Linux 5.10.81
- **Komga version**: v0.143.1-master 
- [ X ] **I am running Komga with Docker**
  - latest
### Describe the bug
in my ComicInfo.xml i have a tags field like this
```
<?xml version="1.0" encoding="utf-8"?>                                                                           
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">   
     .....                                                             
   <Tags>tag1, tag2, tag3</Tags>      
     .....                                                                    
</ComicInfo>  
```
there are other fields as well Im not sure why there not being read 
I would like to have everything generated in the cbz of this [project](https://github.com/RicterZ/nhentai) to be read if that possible 

### Expected behavior
it to read CSV list of tags

### Actual behavior
an empty tag list
 
* could you point me to where this would be found

**Comment by gotson** [comment] 2022-01-12 01:11
Duplicate of #541

Not a bug.

**Closed by gotson** 2022-01-12 01:11 UTC
