### ISSUE TITLE
Create ComicRack.xml

### ISSUE THREAD

**Issue by YuuichiLV** [gotson/komga#924] opened 2022-07-19 21:35 UTC
I have had issues in the past where the database gets corrupted and I have to reenter all the information again and figure out what was read and what wasn't.

Could it be possible to have Komga create/update the comicrack.xml file for each series/folder? At the basic just have it save all the description and genre information, it could be done at the same time make a change to it.

This would save a lot of problems restoring or moving series between libraries.

Thank You

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-07-19 23:47
Duplicate of #82

**Closed by gotson** 2022-07-19 23:47 UTC
Labels: enhancement
