### ISSUE TITLE
[Feature Request] password reset

### ISSUE THREAD

**Issue by sonostrass** [gotson/komga#503] opened 2021-04-18 07:56 UTC
Hi,
I mainly use komga for kids entertainment.

I'd love some additional features for managing kids user like:
- reset password by the admin (lost password)
- log user connexion (as a first level of user activity logging)

Thanks to consider theses enhancements

sOnO

**Comment by gotson** [comment] 2021-04-18 08:06
Partly duplicate of #160 for the log of connections.

**Closed** 2021-06-28 03:46 UTC
Labels: enhancement
