### ISSUE TITLE
Get "Number" metadata from filename

### ISSUE THREAD

**Issue by emsellwood** [gotson/komga#821] opened 2022-02-28 13:59 UTC
### Describe your suggested feature

Many series have strange or incomplete numbering, or people don't have complete collections of issues all the way back to the start of a series. 

Right now numbering just starts at 1 for whatever book is alphabetically 1st in the folder, unless there is metadata in the ComicInfo.xml. This breaks imported reading lists as they just use the folder numbering if no number value is present. 

It would be nice if the metadata for "Number" could be updated similar to the {Series} ({Volume}) update from the folder name using a format in the filename. This way numbers could be accurate without needing ComicInfo.xml files for every file. 

Eg.

- {Series} ({Volume})
    - {Series} ({Volume}) #{Number}.ext
    - {Series} ({Volume}) #{Number}.ext

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-02-28 14:02
Duplicate of #537 and #700

**Closed by gotson** 2022-02-28 14:02 UTC
Labels: enhancement

**Comment by gotson** [comment] 2022-02-28 14:04
> This breaks imported reading lists as they just use the folder numbering if no number value is present.

Reading lists import is made to import lists made in ComicRack, so metadata in the book is expected. 

> It would be nice if the metadata for "Number" could be updated similar to the {Series} ({Volume}) update from the folder name using a format in the filename.

There is no parsing of folder name.
