### ISSUE TITLE
[Feature Request] Change Cover Image

### ISSUE THREAD

**Issue by calgara12** [gotson/komga#165] opened 2020-05-25 06:16 UTC
### Describe the solution you'd like
Some Manga Books in my collection have a Logo of the tranlators as its first page, this will then get used as the cover image for the whole manga series. It would be cool if you could manually define a Cover Image, with either an image upload, or just specify a link to the picture.

Thanks for your hard work!

**Comment by gotson** [comment] 2020-05-25 06:20
duplicate of #63

**Closed by gotson** 2020-05-25 06:20 UTC
