### ISSUE TITLE
[Feature Request] Add Alphabetique ordrer librairies

### ISSUE THREAD

**Issue by mathi54** [gotson/komga#251] opened 2020-07-27 18:24 UTC
Hello, Thank you again for all the great work done.

I have a query that we could choose, between sorting the library as it is currently with several pages or choosing to sort the Libraries in alphabetical order.

**Comment by gotson** [comment] 2020-07-27 23:54
Hi,

i'm not sure to understand what you want. Can you please follow the template next time ? It is there for a reason.

The series are already sorted by alphabetical order, and you can also change the ordering using the sort button in the toolbar:
<img width="205" alt="Screenshot 2020-07-28 at 07 53 31" src="https://user-images.githubusercontent.com/2139133/88603422-776d7780-d0a7-11ea-96cb-de83d23b3f06.png">

**Comment by mathi54** [comment] 2020-07-28 00:07
Hello, a small sort which would allow to have this kind of sorting
![pagination](https://user-images.githubusercontent.com/61603812/88604133-0615d080-d077-11ea-852f-bc207413552d.jpg)

**Comment by gotson** [comment] 2020-07-28 00:12
Duplicate of #186

**Closed by gotson** 2020-07-28 00:12 UTC
