### ISSUE TITLE
Smart Collections

### ISSUE THREAD

**Issue by jakem742** [gotson/komga#828] opened 2022-03-05 03:09 UTC
### Describe your suggested feature

Add the option to create smart collections with filters for series/issue title matches, publisher, publication year/date, read status etc. The possibilities are endless. :) An example could be a smart collection where Series Title includes "Civil War II" and publication year = 2016. I also like to have collections for various characters, so a collection where Series Title contains "Thor" would be nice for keeping them all together.

I find myself manually moving lots of comics into collections based on common groupings that could very easily be converted into filters that automatically update when new series are imported into Komga. I imagine my collection is fairly small, but even with 96 series it is becoming a pain to keep track of what is in the collection and ensuring they're up to date.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-03-05 03:28
Duplicate of #200

**Closed by gotson** 2022-03-05 03:28 UTC
Labels: enhancement
