### ISSUE TITLE
Order issues of a reading list by publication date

### ISSUE THREAD

**Issue by Bazzu85** [gotson/komga#846] opened 2022-03-24 23:06 UTC
### Describe your suggested feature

When in a reading list with multiple series issue, the order is by Series name and his issues.
If a story arc need to be readed across series ordered by pub date is a pain.
example:
![image](https://user-images.githubusercontent.com/7345587/160024317-51ef22fb-1b87-4d56-8688-391c1d86c1fe.png)
![image](https://user-images.githubusercontent.com/7345587/160024335-0a3084f0-f812-4a7e-b6d9-6f83283bc70e.png)
![image](https://user-images.githubusercontent.com/7345587/160024340-a1e2ed1d-209c-4dbd-a7e1-f23a6e6b13ae.png)

Why don't you add a "Order issues by pubblication date" button in reading list edit?

thx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-03-25 01:32
Duplicate of #637

**Comment by Bazzu85** [comment] 2022-03-25 22:03
I didn't found it...thx

**Comment by Rumik** [comment] 2023-01-26 10:04
I'd like to express my interest in this. Having a Sort Order for Publication Date for everything would make putting things in the correct order much, much quicker.

**Closed** 2023-02-22 09:10 UTC
Labels: enhancement
