### ISSUE TITLE
Mark a page for auto deletion while reading

### ISSUE THREAD

**Issue by mcoutinhof** [gotson/komga#1436] opened 2024-02-22 09:30 UTC
### Describe your suggested feature

On Komga Web, while reading a book, let me mark a page for auto deletion, so I can easily remove trash pages from my library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2024-02-23 04:52
Duplicate of #800

**Closed by gotson** 2024-02-23 04:52 UTC
Labels: triage
