### ISSUE TITLE
The Windows client displays garbled characters

### ISSUE THREAD

**Issue by ghost** [gotson/komga#1378] opened 2024-01-03 10:27 UTC
### Steps to reproduce

1. Open the Windows client
2. Right-click on it
3. The option is garbled
![image](https://github.com/gotson/komga/assets/112467275/d96af349-1c76-4c18-a468-e519e649955e)

### Expected behavior

The options are displayed normally

### Actual behavior

The option is garbled

### Logs

[komga.log](https://github.com/gotson/komga/files/13817911/komga.log)

### Komga version

v1.9.2-master

### Operating system

Windows 11

### Installation method

from download.komga.org

### Other details

Windows 11 22631.2715 Chinese Home Edition

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by DieselTech** [comment] 2024-01-03 13:58
Duplicate of #1357 

Read that thread and see if there is something you can help with.

**Closed as completed** 2024-01-04 01:38 UTC
Labels: triage
