### ISSUE TITLE
Ability to upload from web UI from remote

### ISSUE THREAD

**Issue by billsargent** [gotson/komga#850] opened 2022-03-26 20:14 UTC
### Describe your suggested feature

I'd like to see the ability to upload a zipped comic from the UI. Have the system check that its a valid format once uploaded and then placed into either an upload library where it can be later moved to the appropriate library, or have the user specify a library it should go in and have it sit pending approval in the admin interface. This would also include the ability to move comics and collections between libraries.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-03-27 00:12
Duplicate of #70

**Closed** 2022-05-02 07:05 UTC
Labels: wontfix
