### ISSUE TITLE
[Feature Request] Saved queries

### ISSUE THREAD

**Issue by Kawaizombi** [gotson/komga#669] opened 2021-09-10 12:17 UTC
### Is your feature request related to a problem? Please describe.
It's very tiring to type full text search queries each time(especially when using tachiyomi because of virtual keyboard)

### Describe the solution you'd like
Give ability to save query as an entity that can be used later in search by checking checkbox just like tag or genre. How I see it, add section in account setting or server settings or in both(in that case some of queries will be available for all users and some of them will be private) where user can create/edit/delete queries, for example:

Query name: `Single`
Query text: `boot_count:1`

Also it can be helpful to create alias for some genres/tags, for example if we have two genres that have slightly different spelling, for example:

Query name: `Sci-fi`
Query text: `genre:sci-fi OR genre:"sci fi"`

**Comment by gotson** [comment] 2021-09-10 12:32
Duplicate of #200 

> Also it can be helpful to create alias for some genres/tags, for example if we have two genres that have slightly different spelling, for example:
> 
> Query name: `Sci-fi`
> Query text: `genre:sci-fi OR genre:"sci fi"`

You better fix your data in that case.

**Closed by gotson** 2021-09-10 12:32 UTC
