### ISSUE TITLE
Enhancments To Search Results View

### ISSUE THREAD

**Issue by austin-joseph** [gotson/komga#1382] opened 2024-01-07 17:10 UTC
### Describe your suggested feature

Currently search results are displayed as two rows. One for matching Books one for matching Series. 

When there are a large number of results it can be tedious to scroll through these rows to find the item I am looking for.

It would nice to have the ability to expand the search results to a view more similar to the Browse Library view, a grid that overflows items vertically instead of locking them in a row. 

Below is a mockup for a potenial way to switch between these views. 
- All shows the currently existing view and is the default.
- Series and Books show a grid similar to the Libraries/Browse view.

![image](https://github.com/gotson/komga/assets/17039388/20253f27-b021-4c82-98af-3c5f18001da1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2024-01-08 01:45
duplicate of #1103

**Closed by gotson** 2024-01-08 01:45 UTC
Labels: triage
