### ISSUE TITLE
[Feature Request] Search as its own page

### ISSUE THREAD

**Issue by gerroon** [gotson/komga#111] opened 2020-03-11 18:47 UTC
### Is your feature request related to a problem? Please describe.
The search results are only shown in a pull down menu.

### Describe the solution you'd like
It would be nice to have the search results in its own results page

### Describe alternatives you've considered or other apps that can do what you want
Ubooquity can show the search results as an actual page.

### Additional context

There are 2 issues with the current search method.

- The user makes a search and opens a book from the resulting pull down. When the user goes back to click on another book from the search, the search results are not there naturally. The user has to perform the search again, this is especially tedious on a mobile device

- It looks like not all search results shown, guessing that there is a limitation to the pull down menu

**Comment by gotson** [comment] 2020-03-11 23:40
Duplicate of #29

**Closed by gotson** 2020-03-11 23:40 UTC
