### ISSUE TITLE
[Feature Request] Embbed tags added with Komga to cbz files.

### ISSUE THREAD

**Issue by Darkwolf1515** [gotson/komga#289] opened 2020-08-25 22:32 UTC
### Is your feature request related to a problem? Please describe.
I don't like the idea of inputting all this metadata if it will just be wiped if I ever move away from the program.

### Describe the solution you'd like
(If its possible) I would like to embed all of the tags I've edited in program to a open standard within the cbz.

**Comment by gotson** [comment] 2020-08-25 23:26
Duplicate of #82

**Closed by gotson** 2020-08-25 23:26 UTC
