### ISSUE TITLE
Full Text Search results display

### ISSUE THREAD

**Issue by Shakahron** [gotson/komga#1410] opened 2024-01-28 03:43 UTC
### Describe your suggested feature

Currently the only way to filter search results by AND is to us FTS. This is fine, I would prefer it I could use the check boxes to filter AND but it is what it is. 

Would it be possible to display search results with FTS the same way they are displayed with the check boxes? If I want to to use FTS, search results for series are displayed in one row in a very limited amount where the only way to navigate is to click a scroll arrow. I know it probably wouldn't be simple, as search results also displays books, read lists and collections, but there has to be a better way to filter by AND that doesn't make it 10x more difficult parse the results.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2024-01-29 01:41
Duplicate of #1103

**Closed by gotson** 2024-01-29 01:41 UTC
Labels: triage
