### ISSUE TITLE
tray menu not showing chinese characters on Windows

### ISSUE THREAD

**Issue by kofzhanganguo** [gotson/komga#1357] opened 2023-12-18 05:30 UTC
### Steps to reproduce

In komga-1.9.2 version, the tray options are still garbled boxes.

### Expected behavior

In komga-1.9.2 version, the tray options are still garbled boxes.

### Actual behavior

![image](https://github.com/gotson/komga/assets/32073931/9b610c40-c1b7-4ec6-a611-8541d37f6a29)

Even if I delete all the folders on the C drive, C:\Users\Administrator\AppData\Local\Komga, and then use Komga again, after opening the tray, the boxes are still garbled.

### Komga version

komga-1.9.2-windows-amd64

### Operating system

Windows 10

### Installation method

from download.komga.org

### Other details

![image](https://github.com/gotson/komga/assets/32073931/c400cef1-42a3-4fb7-b138-a1bbb884a6ec)

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by kofzhanganguo** [comment] 2023-12-18 05:32
If it is really impossible to solve the problem of garbled characters on the pallet, then the final solution is not to localize the English language of the pallet and only keep the English language without using the Chinese translation.

**Comment by HNQX** [comment] 2023-12-18 06:34
have the same issue 
set the language to english, but still not work
![image](https://github.com/gotson/komga/assets/32836634/05128413-75a4-4c79-ae9b-4b1690031272)

**Comment by kofzhanganguo** [comment] 2023-12-18 06:39
> 有同样的问题 将语言设置为英语，但仍然失效 ![图像](https://private-user-images.githubusercontent.com/32836634/291171116-05128413-75a4-4c79-ae9b-4b1690031272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODE2MzksIm5iZiI6MTcwMjg4MTMzOSwicGF0aCI6Ii8zMjgzNjYzNC8yOTExNzExMTYtMDUxMjg0MTMtNzVhNC00Yzc5LWFlOWItNGIxNjkwMDMxMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA2MzUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyM2QxY2ZmYjJkYjY3ZTY3YWY2NWZmMTUxNTRjYzRjNmVlODliYjgwN2E1ZTVhNzliMmE5MjU0MmM4NjJiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wotj7nsDYOK2rUBiIUeoURSHtdkQrFC5TW5i8OSeR4E)

这个托盘的语言是跟随系统语言的，不是在WEBUI中设置成英文就可以解决的问题，如果实在是解决不了，那么我只能把中文翻译删除，保持托盘的选项为默认英文语言，就像1.8.4版本一样，不进行桌面托盘的本地化翻译就可以了。

**Comment by gotson** [comment] 2023-12-18 06:41
> have the same issue set the language to english, but still not work ![image](https://private-user-images.githubusercontent.com/32836634/291171116-05128413-75a4-4c79-ae9b-4b1690031272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODE5ODQsIm5iZiI6MTcwMjg4MTY4NCwicGF0aCI6Ii8zMjgzNjYzNC8yOTExNzExMTYtMDUxMjg0MTMtNzVhNC00Yzc5LWFlOWItNGIxNjkwMDMxMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA2NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OTZlYjcyNjI0ZWI1MWY5YzJjZjAyNWMzYWVlNDhmOTE3MWUzY2ZmNmRhN2ZiNThhMDQ4NWIxMzAwYTllM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YR75oDq1ayu4tDjiGELA7tdQFtiFBcVu53_iiUCaTQo)

it uses the locale of your system

**Comment by gotson** [comment] 2023-12-18 06:42
It works on my Mac when setting the locale to Chinese, i don't have a Windows machine to reproduce.

**Comment by kofzhanganguo** [comment] 2023-12-18 06:45
> It works on my Mac when setting the locale to Chinese, i don't have a Windows machine to reproduce.

That means that the Windows system problem cannot be solved, so I can only delete the Chinese localized translation. The tray icon of the Windows system will still be displayed in the English language. This can at least ensure that the box is not garbled.

**Comment by gotson** [comment] 2023-12-18 06:50
> > It works on my Mac when setting the locale to Chinese, i don't have a Windows machine to reproduce.
> 
> That means that the Windows system problem cannot be solved, so I can only delete the Chinese localized translation. The tray icon of the Windows system will still be displayed in the English language. This can at least ensure that the box is not garbled.

or you can try to find the issue and submit a PR

**Comment by gotson** [comment] 2023-12-18 06:51
<img width="107" alt="image" src="https://github.com/gotson/komga/assets/2139133/5fc1462a-03cb-4b1b-8ead-7c334c224a0b">

this is what i get

**Comment by kofzhanganguo** [comment] 2023-12-18 06:56
> > > It works on my Mac when setting the locale to Chinese, i don't have a Windows machine to reproduce.
> > 
> > 
> > That means that the Windows system problem cannot be solved, so I can only delete the Chinese localized translation. The tray icon of the Windows system will still be displayed in the English language. This can at least ensure that the box is not garbled.
> 
> or you can try to find the issue and submit a PR

I am just a software user and one of the Chinese localization personnel. Your tray option is to display Chinese, which is correct, but the Windows system is all square, so I want to delete the Chinese translation of the tray on the weblate website. In order to achieve the goal that garbled characters will not be displayed on Windows systems, because most users still use Windows systems, so in order to solve this problem, the only way is to not translate the tray options into Chinese localization. It has been achieved that garbled characters will not appear on multiple platforms, and it will still remain in English. Option status, I don’t know how to edit and produce software, so I can’t find the problem.

**Comment by HNQX** [comment] 2023-12-18 07:14
> > > > It works on my Mac when setting the locale to Chinese, i don't have a Windows machine to reproduce.
> > > 
> > > 
> > > That means that the Windows system problem cannot be solved, so I can only delete the Chinese localized translation. The tray icon of the Windows system will still be displayed in the English language. This can at least ensure that the box is not garbled.
> > 
> > 
> > or you can try to find the issue and submit a PR
> 
> I am just a software user and one of the Chinese localization personnel. Your tray option is to display Chinese, which is correct, but the Windows system is all square, so I want to delete the Chinese translation of the tray on the weblate website. In order to achieve the goal that garbled characters will not be displayed on Windows systems, because most users still use Windows systems, so in order to solve this problem, the only way is to not translate the tray options into Chinese localization. It has been achieved that garbled characters will not appear on multiple platforms, and it will still remain in English. Option status, I don’t know how to edit and produce software, so I can’t find the problem.

Support only set the tray option to english to prevent square..block or something. After all, there are only 4 option and they are not usually clicked in daily moment. As long as the web UI works.

**Comment by kofzhanganguo** [comment] 2023-12-18 07:17
> > > > > 当将语言环境设置为中文时，它可以在我的 Mac 上运行，我没有 Windows 机器可以重现。
> > > > 
> > > > 
> > > > 那意味着Windows系统问题无法解决，所以我只能删除中文本地化翻译。 Windows系统的托盘图标仍将以英文显示。这样至少可以保证盒子不乱码。
> > > 
> > > 
> > > 或者您可以尝试查找问题并提交 PR
> > 
> > 
> > 我只是一名软件用户，也是一名中文本地化人员。你的托盘选项是显示中文，这是正确的，但是Windows系统都是方形的，所以我想删除weblate网站上托盘的中文翻译。为了达到在Windows系统上不会显示乱码的目标，因为大多数用户仍然使用Windows系统，所以为了解决这个问题，唯一的办法就是不将托盘选项翻译成中文本地化。已经做到了多平台不会出现乱码，依然保持英文。选项状态，我不会编辑制作软件，所以找不到问题所在。
> 
> 仅支持将托盘选项设置为英文，以防止方形..块或其他东西。毕竟只有4个选项，而且在日常情况下通常不会被点击。只要 Web UI 可以工作。

如果作者解决不了这个问题，那么我只能删除托盘的中文翻译，还是保持英文状态，不然Windows版是乱码，webUI的中文本地化我始终都在进行汉化，这个是不会变的。

**Comment by gotson** [comment] 2023-12-18 07:19
If no one with Windows is going to look at this, it's unlikely to get resolved.

Chinese windows has a history of not handling UTF-8 properly. The translation files are in UTF-8. not just for Chinese, but also for other languages using non-ASCII characters like French, Finnish or Spanish.

**Comment by kofzhanganguo** [comment] 2023-12-18 07:22
> If no one with Windows is going to look at this, it's unlikely to get resolved.
> 
> Chinese windows has a history of not handling UTF-8 properly. The translation files are in UTF-8. not just for Chinese, but also for other languages using non-ASCII characters like French, Finnish or Spanish.

There are also many Chinese users, but this problem cannot be solved, so I will delete the Chinese translation of the tray and keep the English option on the tray. Otherwise, the menu will be garbled and even more incomprehensible.

**Comment by kofzhanganguo** [comment] 2023-12-18 07:29
![image](https://github.com/gotson/komga/assets/32073931/31779a28-42db-465b-ac16-c32c690bd56d)

All Chinese translations have been deleted, and the problem of Chinese garbled characters will be solved in the next version.

**Comment by gotson** [comment] 2023-12-18 07:33
> but this problem cannot be solved,

if no one tries, yes it cannot be solved. If none of those chinese users want to help, it will not be solved.

**Comment by kofzhanganguo** [comment] 2023-12-18 07:40
> > but this problem cannot be solved,
> 
> if no one tries, yes it cannot be solved. If none of those chinese users want to help, it will not be solved.

Thanks to the author for the answer. It is enough to keep the tray menu options in English. There are not many options to set the tray menu options. I hope to add more parameter settings in the WEBUI, such as the storage location of the database file, etc. Now By default, it is under the C drive. I hope that there will be some option parameters in the WEBUI to more intuitively set the storage location path of the database, etc., instead of letting ordinary users adjust the configuration file.

**Comment by Eisaichen** [comment] 2023-12-23 12:04
I tried on my Win10 and Win11 PCs and can confirm this will happen.
May not be a big problem since there are only 4 options for the tray icon.
I believe this might be a problem with font instead of coding. when the coding is incorrect you usually will give random characters, but what we get is square icons. this commonly happens when the font used does not include the character. For example, if a font file only has less than 500kb, then it certainly will not include Chinese characters.

**Comment by gotson** [comment] 2024-02-08 03:30
closing as the translations were removed, and still cannot reproduce

**Closed by gotson** 2024-02-08 03:30 UTC
Labels: cannot reproduce
