### ISSUE TITLE
[Bug] Komga shows old comics in recently added books/series

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#346] opened 2020-10-22 13:25 UTC
### Komga environment
- **OS**: 
- **Komga version**: 
Docker - v0.64.0-master
### Describe the bug
I found this issue couple of versions ago (not 100% which one exactly). All of the sudden Komga started showing old series as recently added (I have around 30 or 40 series with this issue):

![Screenshot from 2020-10-22 09-10-12](https://user-images.githubusercontent.com/16859916/96876567-9b421e80-1446-11eb-93a9-9c237e5df0da.png)

and - The first 3 are fine but "House of M" is a series I had for a long time.

![Screenshot from 2020-10-22 09-10-40](https://user-images.githubusercontent.com/16859916/96876587-a137ff80-1446-11eb-9d67-97ce610a8dd3.png)

Also if I go to the Library section and choose order by date added or updated (both show the same order of comics):

![Screenshot from 2020-10-22 09-12-48](https://user-images.githubusercontent.com/16859916/96876799-dfcdba00-1446-11eb-9cc0-8d7d77844957.png)

I thought that maybe some script or process have updated my comics but I checked and the timestamp of the comic files is ok, for example "House of M" below:

![Screenshot from 2020-10-22 09-15-44](https://user-images.githubusercontent.com/16859916/96877465-aba6c900-1447-11eb-9f07-e30bd2457d8b.png)

### Steps to reproduce
1. Go to Home
2. Check the "Recently .." sections

### Expected behavior
Recently added series should not list old series.

### Actual behavior
Recently added sections should show new series/books added.

**Comment by gotson** [comment] 2020-10-22 14:03
Can you provide the json of the impacted series and books? You can get them from the swagger.

**Comment by cesalo** [comment] 2020-10-23 04:08
I thinks this is what you need:

> {"id":"02XEW37TMYFQK","libraryId":"3","name":"Superior Spider-Man (2018)","url":"/XXXX/Marvel/Superior Spider-Man (2018)","created":"2020-10-17T09:15:27","lastModified":"2020-10-17T09:15:27","fileLastModified":"2020-01-03T09:07:07","booksCount":12,"booksReadCount":0,"booksUnreadCount":12,"booksInProgressCount":0,"metadata":{"status":"ONGOING","statusLock":false,"title":"Superior Spider-Man","titleLock":false,"titleSort":"Superior Spider-Man","titleSortLock":false,"summary":"","summaryLock":false,"readingDirection":"","readingDirectionLock":false,"publisher":"Marvel","publisherLock":false,"ageRating":null,"ageRatingLock":false,"language":"en","languageLock":false,"genres":["superhero"],"genresLock":false,"tags":[],"tagsLock":false,"created":"2020-10-17T09:15:27","lastModified":"2020-10-17T10:20:10"}}

Looking at this it says that it was created on 2020-10-17 but these are old comics.
I went to the logs and found the one from Oct-17 and found thid message:

> 2020-10-17 05:05:29.995  INFO 1 --- [DefaultMessageListenerContainer-1] o.g.komga.domain.service.LibraryScanner  : Deleting series not on disk anymore: [Series(name=Doctor Strange and the Sorcerers Supreme (2016), url=file:/XXXX/Doctor%20Strange%20and%20the%20Sorcerers%20Supreme%20(2016)/, fileLastModified=2018-12-27T10:09:50.386, id=02W3AE2NGY6RX, libraryId=3, createdDate=2020-10-12T23:47:02, lastModifiedDate=2020-10-12T23:47:02), Series(name=Infinity Countdown Prime (2018), url=file:/XXXX/Marvel/Infinity%20Countdown%20Prime%20(2018)/, fileLastModified=2020-04-15T21:34:07.704, id=02W3AE2S4YBP4 ... 

and a bunch of series specified for deletion but these folders/files were not deleted so not sure why could be causing this.

**Comment by gotson** [comment] 2020-10-23 05:42
Are your files on a network share like nfs or similar?

**Comment by cesalo** [comment] 2020-10-23 10:48
Yes .. in a NAS .. I have Plex, Jellyfin and a bunch of apps including
Komga.

**Comment by gotson** [comment] 2020-10-23 11:14
Can you check if your komga library directly points to the mount point of the nfs share?

If that's the case, when the nfs share is not available, Komga will see an empty root folder for the library root, and will remove all series. 

It's a good practice to not point a library root at the mount point, but at a subfolder instead, that way the root of the library will be unavailable instead of appearing empty, and the scan will fail.

**Comment by cesalo** [comment] 2020-10-23 11:29
I have this setup:
<Mount Point>/comics
<Mount Point>/movies
<Mount Point>/tvshows
Etc.
So yes it's in a subfolder, also all my comics are in the same subfolder so
this would have affected my whole comic library.

**Comment by gotson** [comment] 2020-10-23 11:48
Well, I don't have more ideas, and there's only so much the logs can show.

I'll close this as the system behaves normally, showing recently added books and series.

**Closed by gotson** 2020-10-23 11:48 UTC

**Comment by cesalo** [comment] 2020-10-24 05:45
I found that the scan that caused these series to be deleted took much longer than usual:

> 2020-10-17 05:05:29.988  INFO 1 --- [DefaultMessageListenerContainer-1] o.g.k.domain.service.FileSystemScanner   : Scanned 515 series and 4349 books in 330s

A Normal scan took around 8s:

> 2020-10-17 05:15:08.289  INFO 1 --- [DefaultMessageListenerContainer-1] o.g.k.domain.service.FileSystemScanner   : Scanned 631 series and 5443 books in 8.28s

It's there a way to make Komga put any missing files in kind of a "Recycle Bin" that way if these files are present in a consecutive scan it won't need to recreate them. I believe Plex has a similar functionality.

Thanks for reviewing this issue.

**Comment by gotson** [comment] 2020-10-24 06:03
See #217

**Comment by cesalo** [comment] 2020-10-24 13:49
Thanks. Sorry, last question. If I want to fix this manually .. what is the option: using the API or modify it directly in the DB?

**Comment by gotson** [comment] 2020-10-24 13:52
I don't really see why you would want to change that. New comics will show up as normal when you add more.

You can't change it by API, it's a generated field that cannot be overiden.

I cannot recommend changing anything in the database, do it at your own risk.

**Comment by cesalo** [comment] 2021-07-29 13:53
@gotson - Hi saw finally the recycle bin was implemented but for some reason this issue persists:
Old comics that haven't been modified are showing as new.
This one for example:

```
{
  "id": "05P6PN8SVBYC7",
  "name": "House of M (2015)",
  "url": "/xxxx/Marvel/House of M (2015)",
  "meta-title": "House of M (2)",
  "Created": "2021-07-20T02:33:03",
  "LastModified": "2021-07-27T18:42:37",
  "FileLastMod": "2019-01-22T21:20:54"
}
```

Looking at the logs it seems this series was soft deleted:

```
2021-07-27 14:11:48.348  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookLifecycle   : Soft delete books: [
 Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847, fileSize=41598269, fileHash=p4hj0q, number=1, id=05R1TA3CTY664, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-25T17:00:29, lastModifiedDate=2021-07-25T17:01:03.504), Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300, fileSize=46918763, fileHash=eh07km, number=4, id=05R1TA3CTY665, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-25T17:00:29, lastModifiedDate=2021-07-25T17:01:03.505)
```

and then added/restored back:

```
2021-07-27 14:42:21.317  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Series changed on disk, updating: Series(name=House of M (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/, fileLastModified=2019-01-22T21:20:54.626, id=05P6PN8SVBYC7, libraryId=3, bookCount=4, deletedDate=2021-07-27T14:11:48.320, createdDate=2021-07-19T22:33:03, lastModifiedDate=2021-07-27T14:11:48.908)
2021-07-27 14:42:21.343  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Adding new books: [Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847737, fileSize=41598269, fileHash=, number=0, id=05RNHV8ZJ85T1, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604667, lastModifiedDate=2021-07-27T14:16:04.604668), Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300072, fileSize=46918763, fileHash=, number=0, id=05RNHV8ZJ85T2, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604802, lastModifiedDate=2021-07-27T14:16:04.604802), Book(name=House of M 002 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20002%20(2015).cbz, fileLastModified=2019-01-22T21:20:41.410838, fileSize=36380659, fileHash=, number=0, id=05RNHV8ZJ85T3, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604867, lastModifiedDate=2021-07-27T14:16:04.604868), Book(name=House of M 003 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20003%20(2015).cbz, fileLastModified=2019-01-22T21:20:46.916938, fileSize=42848702, fileHash=, number=0, id=05RNHV8ZJ85T4, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604926, lastModifiedDate=2021-07-27T14:16:04.604927)]
2021-07-27 14:42:21.371  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Try to restore books: [Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847737, fileSize=41598269, fileHash=, number=0, id=05RNHV8ZJ85T1, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604667, lastModifiedDate=2021-07-27T14:16:04.604668), Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300072, fileSize=46918763, fileHash=, number=0, id=05RNHV8ZJ85T2, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604802, lastModifiedDate=2021-07-27T14:16:04.604802), Book(name=House of M 002 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20002%20(2015).cbz, fileLastModified=2019-01-22T21:20:41.410838, fileSize=36380659, fileHash=, number=0, id=05RNHV8ZJ85T3, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604867, lastModifiedDate=2021-07-27T14:16:04.604868), Book(name=House of M 003 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20003%20(2015).cbz, fileLastModified=2019-01-22T21:20:46.916938, fileSize=42848702, fileHash=, number=0, id=05RNHV8ZJ85T4, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604926, lastModifiedDate=2021-07-27T14:16:04.604927)]
2021-07-27 14:42:21.374  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.infrastructure.hash.Hasher     : Hashing: /xxxx/Marvel/House of M (2015)/House of M 001 (2015).cbz
2021-07-27 14:42:22.213  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Match found, restore Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847, fileSize=41598269, fileHash=p4hj0q, number=1, id=05R1TA3CTY664, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=2021-07-27T14:11:48.350, createdDate=2021-07-25T17:00:29, lastModifiedDate=2021-07-27T14:11:48.572) into Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847737, fileSize=41598269, fileHash=, number=0, id=05RNHV8ZJ85T1, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604667, lastModifiedDate=2021-07-27T14:16:04.604668)
2021-07-27 14:42:22.273  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.infrastructure.hash.Hasher     : Hashing: /xxxx/Marvel/House of M (2015)/House of M 004 (2015).cbz
2021-07-27 14:42:23.110  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Match found, restore Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300, fileSize=46918763, fileHash=eh07km, number=4, id=05R1TA3CTY665, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=2021-07-27T14:11:48.350, createdDate=2021-07-25T17:00:29, lastModifiedDate=2021-07-27T14:11:48.572) into Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300072, fileSize=46918763, fileHash=, number=0, id=05RNHV8ZJ85T2, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604802, lastModifiedDate=2021-07-27T14:16:04.604802)
2021-07-27 14:42:23.165  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.infrastructure.hash.Hasher     : Hashing: /xxxx/Marvel/House of M (2015)/House of M 002 (2015).cbz
2021-07-27 14:42:23.836  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Match found, restore Book(name=House of M 002 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20002%20(2015).cbz, fileLastModified=2019-01-22T21:20:41.410, fileSize=36380659, fileHash=sua5za, number=2, id=05R1TA3CTY666, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=2021-07-27T14:11:48.350, createdDate=2021-07-25T17:00:29, lastModifiedDate=2021-07-27T14:11:48.573) into Book(name=House of M 002 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20002%20(2015).cbz, fileLastModified=2019-01-22T21:20:41.410838, fileSize=36380659, fileHash=, number=0, id=05RNHV8ZJ85T3, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604867, lastModifiedDate=2021-07-27T14:16:04.604868)
2021-07-27 14:42:23.917  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.infrastructure.hash.Hasher     : Hashing: /xxxx/Marvel/House of M (2015)/House of M 003 (2015).cbz
2021-07-27 14:42:24.695  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Match found, restore Book(name=House of M 003 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20003%20(2015).cbz, fileLastModified=2019-01-22T21:20:46.916, fileSize=42848702, fileHash=3yenim, number=3, id=05R1TA3CTY667, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=2021-07-27T14:11:48.350, createdDate=2021-07-25T17:00:29, lastModifiedDate=2021-07-27T14:11:48.573) into Book(name=House of M 003 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20003%20(2015).cbz, fileLastModified=2019-01-22T21:20:46.916938, fileSize=42848702, fileHash=, number=0, id=05RNHV8ZJ85T4, seriesId=, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:16:04.604926, lastModifiedDate=2021-07-27T14:16:04.604927)
2021-07-27 14:42:41.626  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LibraryContentLifecycle  : Sidecar changed on disk (file:/xxxx/Marvel/House%20of%20M%20(2015)/cover.jpg, refresh Series for ARTWORK: Series(name=House of M (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/, fileLastModified=2019-01-22T21:20:54.626, id=05P6PN8SVBYC7, libraryId=3, bookCount=4, deletedDate=null, createdDate=2021-07-19T22:33:03, lastModifiedDate=2021-07-27T14:42:37.671)
2021-07-27 14:52:20.903  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.BookMetadataLifecycle    : Refresh metadata for book: Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847, fileSize=41598269, fileHash=p4hj0q, number=1, id=05RNHV8ZJ85T1, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.618) with capabilities: [TITLE]
2021-07-27 14:52:20.904  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847, fileSize=41598269, fileHash=p4hj0q, number=1, id=05RNHV8ZJ85T1, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.618), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T1', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:22.214))
2021-07-27 14:52:21.105  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.BookMetadataLifecycle    : Refresh metadata for book: Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300, fileSize=46918763, fileHash=eh07km, number=4, id=05RNHV8ZJ85T2, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619) with capabilities: [TITLE]
2021-07-27 14:52:21.106  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300, fileSize=46918763, fileHash=eh07km, number=4, id=05RNHV8ZJ85T2, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T2', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:23.111))
2021-07-27 14:52:21.394  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.BookMetadataLifecycle    : Refresh metadata for book: Book(name=House of M 002 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20002%20(2015).cbz, fileLastModified=2019-01-22T21:20:41.410, fileSize=36380659, fileHash=sua5za, number=2, id=05RNHV8ZJ85T3, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619) with capabilities: [TITLE]
2021-07-27 14:52:21.395  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 002 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20002%20(2015).cbz, fileLastModified=2019-01-22T21:20:41.410, fileSize=36380659, fileHash=sua5za, number=2, id=05RNHV8ZJ85T3, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T3', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:23.838))
2021-07-27 14:52:21.522  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.BookMetadataLifecycle    : Refresh metadata for book: Book(name=House of M 003 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20003%20(2015).cbz, fileLastModified=2019-01-22T21:20:46.916, fileSize=42848702, fileHash=3yenim, number=3, id=05RNHV8ZJ85T4, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619) with capabilities: [TITLE]
2021-07-27 14:52:21.523  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 003 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20003%20(2015).cbz, fileLastModified=2019-01-22T21:20:46.916, fileSize=42848702, fileHash=3yenim, number=3, id=05RNHV8ZJ85T4, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T4', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:24.697))
2021-07-27 14:56:18.279  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.SeriesMetadataLifecycle  : Refresh metadata for series: Series(name=House of M (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/, fileLastModified=2019-01-22T21:20:54.626, id=05P6PN8SVBYC7, libraryId=3, bookCount=4, deletedDate=null, createdDate=2021-07-19T22:33:03, lastModifiedDate=2021-07-27T14:42:37.671)
2021-07-27 14:56:18.281  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 001 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20001%20(2015).cbz, fileLastModified=2019-01-22T21:20:35.847, fileSize=41598269, fileHash=p4hj0q, number=1, id=05RNHV8ZJ85T1, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.618), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T1', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:22.214))
2021-07-27 14:56:18.418  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 004 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20004%20(2015).cbz, fileLastModified=2019-01-22T21:20:54.300, fileSize=46918763, fileHash=eh07km, number=4, id=05RNHV8ZJ85T2, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T2', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:23.111))
2021-07-27 14:56:18.517  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 002 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20002%20(2015).cbz, fileLastModified=2019-01-22T21:20:41.410, fileSize=36380659, fileHash=sua5za, number=2, id=05RNHV8ZJ85T3, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T3', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:23.838))
2021-07-27 14:56:18.610  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.komga.domain.service.BookAnalyzer    : Get file ComicInfo.xml for book: BookWithMedia(book=Book(name=House of M 003 (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/House%20of%20M%20003%20(2015).cbz, fileLastModified=2019-01-22T21:20:46.916, fileSize=42848702, fileHash=3yenim, number=3, id=05RNHV8ZJ85T4, seriesId=05P6PN8SVBYC7, libraryId=3, deletedDate=null, createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:37.619), media=Media(status=READY, mediaType=application/zip, comment=null, bookId='05RNHV8ZJ85T4', createdDate=2021-07-27T14:42:21, lastModifiedDate=2021-07-27T14:42:24.697))
2021-07-27 14:56:32.921  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.LocalArtworkLifecycle    : Refresh local artwork for series: Series(name=House of M (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/, fileLastModified=2019-01-22T21:20:54.626, id=05P6PN8SVBYC7, libraryId=3, bookCount=4, deletedDate=null, createdDate=2021-07-19T22:33:03, lastModifiedDate=2021-07-27T14:42:37.671)
2021-07-27 14:56:32.921  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.i.m.l.LocalArtworkProvider         : Looking for local thumbnails for series: Series(name=House of M (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/, fileLastModified=2019-01-22T21:20:54.626, id=05P6PN8SVBYC7, libraryId=3, bookCount=4, deletedDate=null, createdDate=2021-07-19T22:33:03, lastModifiedDate=2021-07-27T14:42:37.671)
2021-07-27 14:56:32.944  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.i.m.l.LocalArtworkProvider         : Found file: /xxxx/Marvel/House of M (2015)/cover.jpg
2021-07-27 14:56:44.583  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#0-1] o.g.k.d.service.SeriesMetadataLifecycle  : Aggregate book metadata for series: Series(name=House of M (2015), url=file:/xxxx/Marvel/House%20of%20M%20(2015)/, fileLastModified=2019-01-22T21:20:54.626, id=05P6PN8SVBYC7, libraryId=3, bookCount=4, deletedDate=null, createdDate=2021-07-19T22:33:03, lastModifiedDate=2021-07-27T14:42:37.671)

```

Is there anything that I need to do to so in this case the series is not date updated?

**Comment by gotson** [comment] 2021-07-29 13:57
No, that's by design. Trash bin does not exactly restore old files. It creates a new file, then copies over the metadata and other stuff from deleted files that matches the hash.

**Comment by cesalo** [comment] 2021-07-29 14:02
Thanks for replying - is there a way to now show these kind of updates in the section: "Recently Updated Series". 
For example in Plex: 
When a file is not present for whatever reason and the movie or tvshow is still there, once the file is back in disk the date of the movie/series is not updated.

**Comment by gotson** [comment] 2021-07-29 14:33
I don't plan to change the behaviour.

**Comment by cesalo** [comment] 2021-07-29 14:34
got it - thanks
