### ISSUE TITLE
Merge and Bulk Edit

### ISSUE THREAD

**Issue by TheRonGDD** [gotson/komga#853] opened 2022-03-30 17:55 UTC
### Describe your suggested feature

1. Like Plex add the ability to Merge Series. This sort of happens if the xml has the same Series Group you end up with a collection. Maybe a hide series in collection and show collections in the browse tab option could achieve this. I am running into series that are in separate folders based on year each getting a separate entry even though they have the same series name in their metadata. 

2. Add more options in the bulk edit. Selecting multiple items lacks all fields. Example: "Title" "Sort Title" 
This kind of goes along with Merge in that a series could be slightly mis-named, but belongs together. This could also be resolved with the implementation of a merge feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-03-30 23:54
One series is one folder.

If you have multiple series with the same name and different year, they are most likely volumes, thus not really the same series in Komga terms.

**Comment by TheRonGDD** [comment] 2022-03-31 05:37
I assure you they are series. Just simpler for me to keep them organized that way. I hoped the tags would supersede folder structure. Looking again at the wiki I see this feature under Scanning now. Sorry. 

Hide series in collection and show collections in the browse tab option would still be appreciated. This would be an option on each collection.

**Comment by gotson** [comment] 2022-03-31 06:59
> Hide series in collection and show collections in the browse tab option would still be appreciated. This would be an option on each collection.

Duplicate of #230

**Comment by TheRonGDD** [comment] 2022-04-06 17:21
I appreciate you have a vision for your program, and I can appreciate it for what it is, but some of us have extremely large collections of digital media. I have large collections of digital magazines which came separated by year, and I continued that trend after finding it was simpler to locate specific issues. Finding a frontend such as your program that makes it easier locate issues is what I am after. The "but" here is that many of these programs get abandoned before they are truly completed. Conforming to your specific folder layout would compromise my long-term ability to manage and maintain the media I currently have. It appeared much inspiration for this particular program was plex which ignores, for the most part, the underlying folder structure or allows you to modify what is displayed in the front-end to correct for folder structure or metadata. This is where merge could help a lot.  At this point looking at the front-end as presented is more complex and cluttered than just opening the folders and browsing the file system. Searching the metadata is fantastic though. 

Just to be clear, I intend no disrespect for what you have created. I see where it is going, and it is fantastic for what it is.

**Comment by gotson** [comment] 2022-04-07 01:15
Plex does not ignore the folder structure, it expects the structure to adhere to [its convention](https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/).

**Comment by gotson** [comment] 2022-04-07 03:24
> The "but" here is that many of these programs get abandoned before they are truly completed. Conforming to your specific folder layout would compromise my long-term ability to manage and maintain the media I currently have.

You could use symlinks, so you don't have to modify your existing folder structure, but instead of using the existing folders for Komga's library, you use a new set of folders per series, and inside the series folder you symlink individual issues from the by-year folder.

That way you don't compromise but still reaps benefits.

You would probably need a script that does that for you, and run it regularly so that newly added issues in the by-year folder are automatically symlinked to the by-series folder.

**Comment by TheRonGDD** [comment] 2022-04-07 03:41
> Plex does not ignore the folder structure, it expects the structure to adhere to [its convention](https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/).

Really, they are just pointing out you need to keep TV and Movies in separate folders. As in different libraries should have separate folders. The rest is recommendations/best practice. With Plex I have many sub directories to organize Music and Movies. The frontend completely ignores the folder structure.

Symlinks I had not considered. Thank you for that suggestion.

**Comment by gotson** [comment] 2022-04-07 05:42
> With Plex I have many sub directories to organize Music and Movies. The frontend completely ignores the folder structure.

Komga also ignores whatever structure you have, until the last folder.

Movies are not the best example, given they are single items, not grouped in any way.

Music still needs to be in a folder for plex, and is not a good example either as they don't really use the metadata properly, at least they didn't when I used it.

I don't believe you can have the same series split in different folders (not talking about season folders).

**Comment by csandman** [comment] 2022-04-21 22:02
> Music still needs to be in a folder for plex, and is not a good example either as they don't really use the metadata properly, at least they didn't when I used it.

Music does need to be in an artist folder but it can be split up as much as you want below that. And for metadata, these days Plex prioritizes metadata tags over folder structure for grouping music.  If I had a properly tagged Beatles album in a Metallica folder, it would still show up in Plex under the Beatles because that's how it would be matched by their music metadata agent.  But I could still modify it in Plex to show up under Metallica if I wanted (for whatever reason).

So overall Plex's folder structures have some looseness in how they affect your library organization, and media can always be retagged from within Plex to either be merged with or split from other media.

**Closed** 2022-04-23 06:18 UTC
Labels: wontfix
