### ISSUE TITLE
Ebook support - need feedback on use cases

### ISSUE THREAD

**Issue by gotson** [gotson/komga#221] opened 2020-06-30 01:51 UTC
Ebook support has been requested a few times already (#69 #166 #173).

**I would like to understand better how Komga could help, compared to existing software like Calibre or others.**

---

**If you have an interest with ebooks, could you please share a bit:**

- what exactly you would like Komga to do regarding ebooks ?
- how you manage it at the moment for your current use case / workflow ?
- what is painful in your current workflow that Komga could solve ?

Example: 
- I don't need Komga to do anything with my ebooks
- I use Calibre to manage my ebooks.
  - Calibre retrieves metadata for my books when the metadata is not present in the book file
  - Calibre can perform conversion from and to various ebook formats.
  - Calibre can send ebooks directly to my devices (Kindle device, Kindle on my Android phone/tablet) via email using the Kindle address
  - I use my Kindle or the Kindle app to read my books. Those are stored as documents in my Kindle account and can synchronize reading progress among all my Kindle devices.
- I don't have any pain points in my current process

**Comment by cloudycloud47** [comment] 2020-07-01 14:54
I manage my ebooks using Calibre and my kindle or ebook readers.

I manage my comics with Mylar and Komga (And tachi.)

**Comment by muchtea** [comment] 2020-07-01 22:28
I currently don't see a use case for Komga as an ebook reader unless at least feature parity with calibre-web https://github.com/janeczku/calibre-web can be reached.

I manage my ebooks with calibre and read them with calibre-web.

I don't really have any pain points, apart from the need to have a new calibre-web instance for each calibre db.

**Comment by Cesar-Pythian** [comment] 2020-07-05 13:12
I actually think that bringing ebook support to Komga is a great idea.
- I do use Calibre for metadata and organization (with Lazylibrarian) and occasionally to convert between formats (epub, mobi,etc).
- I tried Calibre-Web but in my tablet (the same one I use for comics) didn't have a good experience also depends on the Calibre db so is not a standalone app.
- I ended up using an android app (moon-reader / Kuboo) to download manually the books I want to read and then go from there. It does a good job in terms of the reading experience but has a lot of short comics in the integration with the ebook server.
- I find the Calibre Desktop app very old fashion and even though is super powerful I wouldn't want to use for day to day reading and as I mentioned I did use Calibre-Web but didn't quite like it in my tablet and haven't used it in a long time (I sill have the docker).
- I like a bit better other apps like bookbrowser and pyshelf.

At the end of the day I don't think this is about if these apps are good or bad at their job (otherwise all the Komga users will be still using Ubooquity) but what about:
- Single reading experience for similar media (Currently using Komga with Comics and Magazines).
- One admin place for similar media (create users, shared libraries, etc).
- Bringing (Komga) a cool, well done app with modern features to the ebook world.

This is kind of the Plex mentality as well - movies, tv-shows, podcasts, etc.
- Imagine have the "Keep Reading", "On Deck" section applied to books together with comics and magazines.
- Imagine seeing you book library together with your comics library organize by author instead of series.
- Imagine the current features and new features coming applied to your e-book library !!.

I'd love to see that and for sure will use it.

**Comment by cesalo** [comment] 2020-07-05 13:14
I actually think that bringing ebook support to Komga is a great idea.

- I do use Calibre for metadata and organization (with Lazylibrarian) and occasionally to convert between formats (epub, mobi,etc).
- I tried Calibre-Web but in my tablet (the same one I use for comics) didn't have a good experience also depends on the Calibre db so is not a standalone app.
- I ended up using an android app (moon-reader / Kuboo) to download manually the books I want to read and then go from there. It does a good job in terms of the reading experience but has a lot of short comics in the integration with the ebook server.
- I find the Calibre Desktop app very old fashion and even though is super powerful I wouldn't want to use for day to day reading and as I mentioned I did use Calibre-Web but didn't quite like it in my tablet and haven't used it in a long time (I sill have the docker).
- I like a bit better other apps like bookbrowser and pyshelf.

At the end of the day I don't think this is about if these apps are good or bad at their job (otherwise all the Komga users will be still using Ubooquity) but what about:

- Single reading experience for similar media (Currently using Komga with Comics and Magazines).
- One admin place for similar media (create users, shared libraries, etc).
- Bringing (Komga) a cool, well done app with modern features to the ebook world.

This is kind of the Plex mentality as well - movies, tv-shows, podcasts, etc.

- Imagine have the "Keep Reading", "On Deck" section applied to books together with comics and magazines.
- Imagine seeing you book library together with your comics library organize by author instead of series.
- Imagine the current features and new features coming applied to your e-book library !!.

I'd love to see that and for sure will use it.

**Comment by hot22shot** [comment] 2020-07-05 19:59
I'm using Calibre to manage my ebook and push them on my Kobo.
I also have a calibre-web instance to access them online.

If

**Comment by BryanWall** [comment] 2020-07-09 16:01
I just discovered Komga while looking for an alternative to Ubooquity, which seems to have been abandoned. I have been using Ubooquity, which fits my use cases better than other tools that have been around for a while, but am frustrated with bugs and issues that will never be fixed since the author has stopped supporting it. It's too slow and I think may be based on an obsolete version of Java. I tried a half dozen other tools before stumbling across Komga. Two of the main reasons that the others don't work for me are

1. Content needs to be copied/duplicated instead of being left in place (like Calibre and other tools that are based on it). I have too much content to have 2 copies of it laying around, and I want to be able to access it from the file system as well as through the media server.
2. Lack of support / project has been abandoned. It seems like most of the eBook media server projects have been abandoned in the last couple of years. There should be a decent amount of demand for a solution that is being actively developed and supported. 

**Here's my list of use cases (and non-use cases) that come to mind:**

1. I have my content already organized in folders on a NAS. The tool should index the content without moving it or changing it in any way.
2. I primarily to use an OPDS client on iPad for reading content (I use Chunky, KYbook 3, and Marvin), but also have a Kindle. OPDS support is required. Being able to view/read content through the web interface is a "nice to have" and I might use it occasionally, but not as important as good OPDS support. Sending to Kindle would also be a "nice to have" feature.
3. Content scanning speed - I have a large number of items and Ubooquity takes hours to scan... I'm not sure how long because it frequently gets stuck during the scanning process (maybe due to issues like the ones that show up under the media analysis section in Komga). Content scanning/indexing, especially for newly added content or newly created libraries, should by done in a way to make the content usable as quickly as possible so if I add a new library I don't have to wait hours just to access it after creating the library. Maybe do an initial scan just to get the content loaded and available, then do a second scan to add metadata. You may already be doing something like this, because items seem to show up faster than Ubooquity.
4. Docker - Need to be able to run the server in a Docker container that's kept up-to-date and working. Also, be efficient with RAM since many people will want to run the container on their NAS instead of a dedicated PC/server.
5. Retrieving metadata would be a nice feature. I've not used Calibre for that, so I don't know what is required for it to work. What types of content is retrieving metadata possible for, and what's required for it to work? Is it based on the filename of the item, or something else?
6. I don't need Komga to be able to convert between formats. There seem to be dozens of tools that already exist to convert between formats. Maybe it could be handled through a plug-in architecture rather than being built in to Komga, if it's something that others want. 

**Here are my requests for Komga after using it for a few days, roughly in order of importance. If these got added to the development queue (especially 1 and 2), I would definitely become a financial supporter through one of your donation options:**

1. Have a view of content based on the existing folder structure of the content within a library (through the web interface and OPDS). I think this feature is one reason a lot of people like Ubooquity. My content is already organized in a folder structure. An example might be Publisher->Series->Year->Issue, or some variation of that. Let me browse the content using the folder structure that's already in place - I know where everything is. It looks like Komga flattened out all of the folders into one level, so right now if I select a library there are dozens of items labeled "January", dozens labeled "Februray", etc. and it's impossible to find what I am looking for. 
2. Fix how item titles are displayed in the web interface. Currently Komga displays 2 lines for the title and a lot of my item titles get cut off. Comics sometimes have titles like "Star Trek - The Next Generation - Perchance to Dream 1". What gets displayed in Komga is "#31 - Star Trek - The Next Gener", and I can't tell what this item is.
3. Have a List or Table view of content rather than just thumbnails. For some types of content, a table type view would be easier to navigate than thumbnails, and you could show metadata in the table. This would also solve the issue of long item titles. 
3a. You could allow bulk editing of metadata in the table view, editing individual items directly in the table, or selecting multiple items for editing things like the publisher or other pieces of metadata that would apply across multiple items. A bulk metadata editor, and maybe even writing the metadata (whether automatically fetched or manually edited) back into the original file (like CBR/CBZ files) could be a must-have feature for a lot of people.

**Comment by xx255q** [comment] 2020-07-10 13:46
Having epub would be great since the files I usually end up getting are epub. And having it all on one platform  would be nice, Ubooquity had already supported it

**Comment by gotson** [comment] 2020-07-10 23:27
> Having epub would be great since the files I usually end up getting are epub. And having it all on one platform would be nice, Ubooquity had already supported it

Please use the template provided. Arguments like "would be great" and "would be nice" do not bring any value to the debate.

**Comment by gotson** [comment] 2020-07-10 23:31
@BryanWall you are mixing a lot of things, and putting everything in your comment. This issue is specifically about supporting ebooks.

Can you use the provided template to expand specifically on the ebooks use case, and not about just every improvement or generalities you would like to see in Komga?

**Comment by stonechitlin** [comment] 2020-07-13 15:03
what exactly you would like Komga to do regarding ebooks ?
Provide basic pdf, epub support in conjunction with read status and current page.

how you manage it at the moment for your current use case / workflow ?
I'm already using komga for my books, they are all in pdf format.

what is painful in your current workflow that Komga could solve ?
epub support with basic text options (size, a few fonts) as well as "paper" or background color options so that I can use komga for all of my reading needs.

**Comment by juligreen** [comment] 2020-07-17 06:11
I tried to use Calibre for my ebooks before, but since I haven't been able to sync reading progress from inside ebook apps with it, it wasn't usable for my and I'm stuck with proprietary solutions for now (i.e. Google play books).

**Comment by Gin-no-kami** [comment] 2020-07-18 14:06
- The minimum feature set is the ability to display ebooks (and their cover image) and their metadata in the library (similar to what is currently done for comic formats) and allow the option to download the ebook. As a stretch feature, being able to read the books in the browser would also be a great feature as I could use web extensions (like Yomichan) to look up unknown words.
- I currently use Calibre/Ubooquity to manage and view my epubs. However, since Ubooquity is Calibre based, it doesn't allow for browsing books by their series (I primarily read light novels which are heavily serialized). 
- Due to bookwalker selling their books in image format, I have half of my light novel library in Komga (as they are .cbz) and the other half in Calibre/Ubooquity. I would like to consolidate them all under Komga, which is what I use to view my library on any device. I already have a replacement script to scrape the epubs metadata from Amazon, so if Komga would just be able to display the ebooks in my library then I would be able to completely remove Calibre/Ubooquity from my workflow and just use Komga for everything.

Thanks for considering ebooks!

**Comment by ultrahumanite** [comment] 2020-07-19 19:38
- I would like Komga to display .epub and .mobi, show cover and meta data, allow reading of the books in the browsers, remember progress, download option, at some point email to kindle option would be nice.

-  Pain point. For audio/video I have Plex handle my music, audiobooks, tv, movies it's all in one place easily accessible and manged by one app. Komga could be a Plex like hub for printed media one place to do almost all my reading and perhaps most importantly allow me to share my library with friends and family via a modern user friendly interface.

**Comment by timo95** [comment] 2020-07-26 09:02
- I would like Komga to display .epub and .cbz (many LNs are in cbz) in their folder structure with cover and metadata. I would like to edit the metadata and download them using opds with koreader.
- I don't use any software to manage my ebooks. They are organized in a custom folder structure and i copy books i want to read to my ebook reader.

**Comment by Shadowfied** [comment] 2020-07-30 09:59
- what exactly you would like Komga to do regarding ebooks ?

I would like Komga to add ebooks just like it does with comics with support for EPUB files.
I would like for OPDS to be supported for this too.

- how you manage it at the moment for your current use case / workflow ?

I read my ebooks on my Kobo Libra and right now I use Kobos built in web browser to access a public FTP I opened which is really not ideal.

- what is painful in your current workflow that Komga could solve ?

Having an open FTP server is not an ideal setup for me. I don't even know if I can use basic auth for it yet, but I could drop this entire setup with Komga supporting ebooks.
I would have a great unified source for all my e-reading needs, and I'd be able to securely consume content through an auth protected and up to date OPDS catalog from my server without having to use, maintain and configure 2 (or even more) separate pieces of software.

**Comment by lukaslangrock** [comment] 2020-08-31 20:12
- I'd love for Komga to get metadata and support eBooks (epub) so I can read them using the webreader or OPDS.
- I currently manage my (few) eBooks using Tolino Webreader, the cloud storage/reader for my ebook reader.
- I always have to upload them to my cloud and it's not self hosted which Komga could solve. Sure, I could setup calibreweb or something but I just have a few ebooks and they are all related to the mangas so having it all in one place would be great.

**Comment by LivingWithHippos** [comment] 2020-09-02 08:03
what exactly you would like Komga to do regarding ebooks ?
I wouldn't want komga to manage my ebook

    how you manage it at the moment for your current use case / workflow ?
I have calibre web installed, it's pretty good and has a lot of useful features. It has opds, send to kinfle, shelves etc. I use komga for my comics because by default I want to see a list of all my books, if I added comics I would have lots of items.
I read from my ebook reader with opds.

    what is painful in your current workflow that Komga could solve ?
Pretty happy with it

**Comment by golserma** [comment] 2020-09-11 13:09
I use komga to read magazines in PDF format.
Everything works fine if I had two wishes .

1. Fulltext search to find an article.
2. Prefetch more pages in advance to make swiping faster.

**Comment by garbled1** [comment] 2020-09-14 14:04
what exactly you would like Komga to do regarding ebooks ?

Basic in-browser support would be nice.

    how you manage it at the moment for your current use case / workflow ?

I don't.  I have very limited need for ebook reading, and am not inclined to install anything to fix that, but I have komga, and love it, so if it had the feature I'd probably import a few here and there.

    what is painful in your current workflow that Komga could solve ?

I have no way of doing this now and don't want another app.

**Comment by edwinbadillo** [comment] 2020-09-19 03:00
> what exactly you would like Komga to do regarding ebooks ?
Support for epub books with the same features as Kogma, creating libraries, collections, series, metadata editor, filters, web reader (with read progress), OPDS, etc. Web reader being a bit flexible: having a few of the standard fonts, allowing some simple styling styling, margin etc. (I currently use Marvin 3 and that does a pretty good job of offering a few options)

> how you manage it at the moment for your current use case / workflow ?
I use Calibre for metadata management and OPDS while reading in Marvin3 (iOS App). for some time I was using the calibre content server's webreader to keep read progress and sync it across devices but the web reader is not great and kept cutting off chapters and causing issues so I had to abandon it. 

> what is painful in your current workflow that Komga could solve ?
Keeping track of what I'm reading and where I left of across devices. I would mainly end up using the webreader for the most part so it maintains my read progress in sync across my devices. Being able to see where I left of in a book series and if I'm I have any books unread would be great. Honestly I'm just spoiled with Plex and Komga and would love to have a similar experience for ebooks, unfortunately the best available now is no where near as good.

**Comment by deafmute1** [comment] 2020-10-19 20:31
I'm rather happy to use calibre+calibre-web+importer script at the moment for my ebooks. But I'm happy to see komga take on ebooks and perhaps switch one day if it gets the features I need done.

Two features needed from calibre-web: The ability to instantly convert from the webui using calibre from epub to mobi (or vice versa) and then to send it to the kindle import email address. It is not necessary to implement a email server (this is difficult for anyone hosting via a home connection anyway due to ISPs firewalling necessary ports often), just allow us to connect to an external SMTP server and facilitate the sending of ebook files over it.

If you are implementing these features, it makes sense to implement [kcc](https://github.com/ciromattia/kcc/) which converts  image archives to mobi as an additional converter backend to calibre, as it could make use of the previously implemented feature-set. Of course, it is a little more complicated then epub to mobi as there are many more options available and some are necessary at minimum to present to user (device profile, manga/webtoon/2panel layout). it may be easier to allow the user to input a number of preselected custom cli arguments for` kcc-c2e.py`.

**Comment by otravers** [comment] 2021-01-04 14:32
I would like to make the case _against_ supporting ebooks if that will be done at the expense of continuing to improve Komga for what it's uniquely good at, which is comics. Calibre is already a very established platform for ebooks that gets updates all the time, while it's not good at comics. With Ubooquity development being abandoned, the case for building Komga as a "Plex for comics" was clear.

It would be a massive effort to match Calibre, which surely would divert resources from comics. If there is a use case for ebooks in Komga, I'd be concerned with scope creep and focus dilution.

**Comment by otravers** [comment] 2021-01-04 14:32
I would like to make the case _against_ supporting ebooks if that will be done at the expense of continuing to improve Komga for what it's uniquely good at, which is comics. Calibre is already a very established platform for ebooks that gets updates all the time, while it's not good at comics. With Ubooquity development being abandoned, the case for bKomga as a "Plex for comics" was clear.

It would be a massive effort to match Calibre, which surely would divert resources from comics. If there is a use case for ebooks in Komga, I'd be concerned with scope creep and focus dilution.

**Comment by cityeyes** [comment] 2021-02-27 03:55
As long as it doesn't interfere with the comics side of things, I'd really like ebook functionality in Komga. Maybe make it optional, or a plugin type thing, so that existing functionality isn't changed for current users, but so that those of us who have ebook libraries could use Komga to serve them.

A lot of people like Calibre, but it's just not an option for me because I don't like how it duplicates my library to use its own organizational system. Plus, I don't want to introduce yet another server to my PC. I LOVE how Komga works with my comics, and would be really happy if it could extend to my ebooks.

Ubooquity, which I migrated to Komga from, deals with both ebooks and comics, but I'd rather stick with Komga because I like that it's in active development, it's constantly improving, and it just _works_, which I really appreciate.

As for the specific questions you asked:


- what exactly you would like Komga to do regarding ebooks ?
I don't need a ton of functionality, honestly. It'd just be nice to be able to read my ebooks on the go using the same server that I use for my comics, since they're both read on the same device. I'd also like to keep my position in my books across platforms, of course. I definitely don't need a "does it all" solution like Calibre, just a way to access my ebooks in the same way I access my comics.

- how you manage it at the moment for your current use case / workflow ?
Currently, I don't have a perfect solution. I either copy my ebooks over to my device manually, or read them via Google Books. I used to use Ubooquity, but switched to Komga. I've tried Calibre, but I don't like how it treats my files and it's honestly just a bit too much for what I need.

- what is painful in your current workflow that Komga could solve ?
I'm trying to reduce my dependence on the Google ecosystem, so being tethered to Google Books isn't perfect. Outside of that, I really don't have any self-hosted options that I'm happy with, since my only alternatives are Ubooquity, which I've left, or Calibre, which does a phenomenal job, but doesn't work how I'd like it.

**Comment by farahnur42** [comment] 2021-03-16 14:19
Just like the poster up above I don't like Calibre's heavy-handed organizational system (that doesn't even work well with the sort of books that I want to read, light novels and webnovels that is) and the metadata scraping in my case has been abysmal even after many tweaks. So:

> what exactly you would like Komga to do regarding ebooks ?
Beyond the oft-repeated metadata support I'd like an improved reader (for example with inverted colours support since I prefer reading white text on black backgrounds and the current reader doesn't allow for that [the background colour is already set to black but that doesn't invert the color of the page]), so I'm more or less asking for the Invert Luma option in Okular. Other than that maybe being able to change out the colour scheme there altogether?

> how you manage it at the moment for your current use case / workflow ?
I don't use anything beyond just going through my library and reading things from the individual folders with Okular, my DE's included reader, because my experience with Calibre has not been positive whatsoever and I have yet to have found a suitable alternative that has both ebook management (or at least serving as an ebook server) capabilities and the capability to read them. I already use ebook-convert to convert all of my epubs to pdf anyways so that's not something that I'm looking for from Komga in particular.  

> what is painful in your current workflow that Komga could solve ?
Just being able to use the same media server for all of my printed media (ebooks, comics and manga), really. Just the fact that Komga respects my library organization is good enough for me as far as library *management* goes.

**Comment by FunWithUrban** [comment] 2021-03-24 01:23
> what exactly you would like Komga to do regarding ebooks ?

All the basics that I need seem to already be in place like OPDS support, editing metadata manually, adding covers, etc. People above have mentioned other great features that would make the experience even better like searching for metadata from external sources and inverted colours.

> how you manage it at the moment for your current use case / workflow ?

 I'm currently using Ubooquity but the experience is not great and development here seems much improved. All I really do now is scan the root folder with Ubooquity and then use and external app with OPDS support for reading.

> what is painful in your current workflow that Komga could solve ?

I love everything I'm seeing from Komga and would love to start using it but I  don't want to have to run two separate services in order to support comics/manga and ebooks.

**Comment by moisesbelda** [comment] 2021-03-26 22:16
**what exactly you would like Komga to do regarding ebooks ?**

Apart from reading in a streaming way like the reading comics feature, it will be nice to have all my reading libraries in one single app and place, Komga. The ODPS support for ebooks will be nice as well.

**how you manage it at the moment for your current use case / workflow ?**

I was using ubooquity (comics) and calibre-web (ebooks). Ubooquity is discontinued and both libraries (comics and ebooks) corrupt the database, and calibre-web doesn't support comics so well.

**what is painful in your current workflow that Komga could solve ?**

The most important for me is to have just one application for rule them all :) I mean, all my reading stuff (books, magazines and ebooks) in one sigle application, with same interface, same way to read.  Komga made me to use just the web browser  to read comics in my tablet instead of using a specific comic books reading app. It would be nice to have the same for ebooks and if possible in the same UI like the comics. For now, I'm satisfied to have the epub library in Komga without reading support (only the pages with images can be read), therefore what I do is to download from komga the epub and import in the epub reader app.

Thanks for your application.

**Comment by frogcrush** [comment] 2021-03-31 20:59
A pain point for me is not being able to stay on the same page between devices, eg between my desktop, laptop, and tablet that I use for reading.

**Comment by ted46045** [comment] 2021-05-26 00:35
- what exactly you would like Komga to do regarding ebooks ?
  Basic epub rendering/reading, no real metadata support needed.  Familiar UI (as comic reading) is nice
-     how you manage it at the moment for your current use case / workflow ?
  Convert .mobi/epub files to pdf and put into a library folder (seperate from comics folder).  Turn off metadata/scanning for comic info

-     what is painful in your current workflow that Komga could solve ?
  No need for converting to pdf, no need to use calibre

**Comment by Darkwolf1515** [comment] 2021-06-10 11:15
**If you have an interest with ebooks, could you please share a bit:** 

- what exactly you would like Komga to do regarding ebooks ?

Honestly? What I want is a way to access my books on my server, through both a web client and a downloadable mobile app, featuring offline downloads for the app, rich epub support (highlights, notes, bookmarks, ect, with a view that lets you jump to them),

- how you manage it at the moment for your current use case / workflow ?

Right now its jellyifn, as it supports epubs, but not very well atm. You can view a book, look at the table of contents, and it will save the last page you left it on, No bookmarks, no highlights, nothing, no download support either.

- what is painful in your current workflow that Komga could solve ?

Honestly I really dont want to use jellyfin for my books, even if the issues above wernt a thing, allowing komga to be my all in one book place sounds like a dream. A viewer with rich epub support thats on my server is what im dying for.

**Comment by GlassedSilver** [comment] 2021-07-28 18:12
I could see this making a lot of sense for [light novel](https://en.wikipedia.org/wiki/Light_novel) readers, which I would rather place besides my manga (and possibly lump them together within the same respective franchise into a collection) rather than managing those separately.

Idk... Calibre is "book" land to me. That and general magazines.

Komga is my manga stuff and light novels to me are much closer to the manga/weeb trope. So... there's that.

This is how I'd use it.

Also lots of the same metadata sources for manga also apply to LNs, so... not sure about metadata agents for Calibre for LNs, but I guess getting solid metadata for LNs would be a good byproduct of having good metadata for manga.

**Comment by TaakoMagnusen** [comment] 2021-09-02 05:07
`what exactly you would like Komga to do regarding ebooks ?`

Display epub/mobi/pdf easily over the server. Keep track of active page across devices, display metadata.cover image.

`how you manage it at the moment for your current use case / workflow ?`

Currently looking into solutions and am only seeing calibre+calibre-web and ubooquity. Neither of which handle cbz/cbr well and have really poor interface. I don't want to calibre because i either have to put all books in its tyranically enforced  one-size-fits-the-sole-developer file structure or have it duplicate all my books to have its way.

`what is painful in your current workflow that Komga could solve ?`

See above. I like komga's interface and i treat my manga/comics the same as epub/mobi/pdfs. I want them all in one palce.

**Comment by Trial-In-Error** [comment] 2021-09-20 18:56
- what exactly you would like Komga to do regarding ebooks ?
  - store ebooks in a less opinionated fashion (eg, not try to order them by series number)
  - read ebooks with page sync
- how you manage it at the moment for your current use case / workflow ?
  - Right now, I don't. I tried just keeping things in cloud storage, but lack of read progress sync, search, collections were killer. I tried Calibre, and hate using it. I tried Komga, and it was a perfect fit (especially user permissions for exposing different libraries to different users), but won't read ebooks.
- what is painful in your current workflow that Komga could solve ?
  - Read progress sync, variable user permissions, and the ability to just use a filesystem. I manage my library's filesystem on one device, which is then synced to my komga server. Calibre, etc, want to be too involved in the act of "import"ing, when I want to think of it more as "add to filesystem, let tools do the rest."


Honestly, for my use case, 2 changes would fully support me:
- Allow series / libraries to have a customizable sort order besides series number. If this is on, hide series number from the title.
- Modify the reader to read ebooks in .epub format.

**Comment by ericma15** [comment] 2022-01-02 17:02
Hey, I use kogma to manage my commic. Now I also want it manage my light novel. I found many many solutions. None can solve it. I think kogma is the closest one. I use to use bookBrowser but it don't have user system. I found the author's open source project [epubviewer](https://github.com/pgaskin/ePubViewer), it can handle both manga and novel. It's under MIT license. maybe interate it can solve some novel's parser?

**Comment by shimizurei** [comment] 2022-01-11 16:24
### Why not the competition?

I've been looking at Kavita for a while since it provides the ability to read light novels out of the box. One of my biggest reasons for not using it at this time though, is that it's UI is so ugly to me. Komga is so much more attractive-looking. I'm someone that won't use an app (no matter how useful) if it's not laid out nicely (looking at you grocy). Komga's flow _just makes sense_.

I've never liked Calibre because it forces me into a file structure I don't use. I have a very complicated file structure and Komga doesn't mind it. It's like "you do you and I'll handle the rest". I like that; I don't want a program dictating how I should organize my data.

Ubooquity is not open source and development has all but halted on it. No thanks.

Komga is by far the prettiest of them all imo.

### What exactly you would like Komga to do regarding eBooks?

I want to be able to read like any eBook. Page by page, not scrolling. With a nice array of a few key fonts/typographical fixings and backgrounds to customize the experience to me. Bookmarks and remembering progress. ToC listing. Highlight and save keys quotes. Search. Basically, most of what Kindle does without tying me to Kindle. As you can probably tell, I don't like being locked in to a process/service (especially if it's not open source), unless I choose to do so myself 😉 

### How you manage it at the moment for your current use case / workflow?

If I *have* to read something, I will download it and read it in Moon+ Reader or buy it from Amazon. I just want one single place to read everything.

As for metadata, I'm following the anansi project, but for right now I throw my metadata into a custom JSON file that lives with its respective eBook file and update the app as needed.

### What is painful in your current workflow that Komga could solve?

Consolidating my workflow to a singular app.

I also think we need a new gold standard when it comes to eBook reading. Calibre has been king for too long.

**Comment by QORTEC** [comment] 2022-04-18 01:39
I currently don't use Komga at all, and without epub support I'm definitely not a target audience. 
I have a growing epub and cbz library and I am looking into ways to (simplify) improve my reading experience.

> what exactly you would like Komga to do regarding ebooks ?

What I'm looking for is a "server" provide epubs via OPDS, allowing me to use my preferred ebook reader.
I would also appreciate the ability to edit the metadata of my epub, since publishers occasionally make poor choices or entirely change formatting... (eg ``Last Name``, ``First Name`` > ``First Name`` ``Last Name``)


> how you manage it at the moment for your current use case / workflow ?

I store my cbz and epubs using a folder structure, and manually copy and paste said folder to the device of my choice.

> what is painful in your current workflow that Komga could solve ?

I use multiple devices to read my library.
- must transfer files to each device;
  library access via a central location (OPDS) would allow full/updated library access on on all devices 
- must take note of read position/progress when switching from one device to another;
  position syncing is a feature available on OPDS 
- Setup of Calibre on a headless server (no monitor/gui) is annoying, and so is their folder/metadata structure...

If you to read via WebUI then the minimum basic features of font family, font size, paragraph spacing, margin size is a must.
If you implement epub support via OPDS only, that would fully satisfy my desired use case.

**Comment by gotson** [comment] 2022-04-18 01:41
> * position syncing is a feature available on OPDS

Can you expand on that? I've been through the opds specification many times, I've never seen anything like that.

**Comment by QORTEC** [comment] 2022-04-18 02:07
@gotson thanks for pointing that out, looks like I will need look into different solution for position syncing.

**Comment by moisesbelda** [comment] 2022-05-13 10:54
Hi @gotson 
Are you considering e-book support or have you ruled it out completely? Are there any technical challenges that make it difficult or not feasible? We would like to hear your opinion after all this feedback.
In any case, with or without this support, your app is amazing.
Thanks

**Comment by mybuntu-git2** [comment] 2022-05-18 16:06
_what exactly you would like Komga to do regarding ebooks ?_
List books, manage libraries, manage users, find duplicates, stream opds - this is all already done.

Maybe handy to have preprocessing scripts for new files that are detected in komga libraries.
This way for example before adding a file to the library, we could manipulate it in various ways: change extensions, move to another location, etc.

_how you manage it at the moment for your current use case / workflow ?_
I use komga as opds server for comics, manuals, novels in epub cbz and pdf formats. The libraries point to my owncloud and I access komga via vpn.
I read only from iPad/iPhone using kybook2.

_what is painful in your current workflow that Komga could solve ?_
Pretty much nothing. I would like the webui to potentially have an even lower footprint by disabling thumbnails and other stuff on demand.
And a cron job that perform the _find duplicates_ action, and sends a mail or drops a file with the list.
maybe possibility to use an external mariadb server.

**Comment by briandking** [comment] 2022-07-15 19:44
what exactly you would like Komga to do regarding ebooks ?
> Provide a multiuser, authenticated interface with read/progress tracking like it does for my comics.

how you manage it at the moment for your current use case / workflow ?
> I use Calbre but don't have read/progress tracking or authentication. Calibre just provides a dumping ground for books and metadata

what is painful in your current workflow that Komga could solve ?
> The lack of multiuser read progress tracking

**Comment by utimukat55** [comment] 2023-09-09 04:15
Hello. Komga is so good ebook reader especially about UI. But some of bad point I feel. It may be unnatural caused by machine translation, I hope to tell my opinion.

I found Komga a few weeks ago and had a docker image ready to go, so I decided to use Komga as an ebook reader.
The ebooks are in epub and I have been using Calibre web.
The ideal form of ebook bookshelf with Komga is generally "can be hosted on ARM (Orange Pi 5)" and "epub files are hosted elsewhere with minio and mounted with rclone for reference".
As for UI, I find Komga better than Calibre web. I find it the best I have ever used for viewing epub, especially using Tachiyomi, and using browser on my phone.
There are two things that Calibre web can do that Komga can't. One is uploading from an epub file via a browser, which I personally would prefer Komga to have. The other is the inability to handle epubs other than images, which I think would be a difficult amount to implement and I would be happy to see it happen in the long term.
One thing that is not good about Komga right now is that when I open a minio epub that is mounted with rclone, the page does not keep up with the loading. Specifically, after trying to view a page and it comes up from a blank, it appears to be loading images for only 2 pages, and then when I view the next page, it goes back to loading images.
I haven't seen the implementation of how the images are loaded, so I'm just guessing, but for now I'm hoping that the open epub is cached somewhere so that the images load more smoothly.

Huge thanks to Komga developers.

**Closed** 2023-11-28 04:40 UTC
Labels: consider, pinned
