### ISSUE TITLE
[Feature Request] Ability to hide libraries as admin user.

### ISSUE THREAD

**Issue by electrona** [gotson/komga#407] opened 2021-02-12 05:03 UTC
### Describe the solution you'd like
As you would untick boxes for a user to hide libraries. This feature should be enabled for the admin user.

### Describe alternatives you've considered or other apps that can do what you want
I could make a user for myself, but I don't want to manage a personal and an admin user to hide a library.

**Comment by gotson** [comment] 2021-02-12 11:20
Can you clarify what's the use case?

Probably a duplicate of #229

**Comment by electrona** [comment] 2021-02-12 17:00
I want to be able to select what libraries I can see, like if I were to select libraries with the checkboxes like for a user account. So I can hide a library for myself, as admin, maybe the library is only for a user and no one else.

**Comment by electrona** [comment] 2021-02-12 19:55
A workaround is to hide read and to mark those comics as read under admin user

**Comment by gotson** [comment] 2021-02-12 23:39
OK so it's a duplicate of #229

**Closed by gotson** 2021-02-12 23:39 UTC
