### ISSUE TITLE
[Feature Request] Update ComicInfo.xml after editing via Web Editor.

### ISSUE THREAD

**Issue by monologconnor** [gotson/komga#754] opened 2021-12-29 20:12 UTC
### Is your feature request related to a problem? Please describe.
Hi, I jut tried the komga via docker and the experience was amazing.
I tried to implement a ComicInfo.xml file within the comic archive for the metadata, but it is a bit hard to write the xml file without a template which shows what kinds of fields were avaliable to komga.

After I update my library via webui, there are still some field left as empty in komga so I tried to edit those fields via komga and saved those editions. However the ComicInfo.xml file in the comic archive was not updated and I think it will be helpful for users to update the ComicInfo.xml in the compressed archive for further library management and also help users to know what the ComicInfo.xml should looks like.

### Describe the solution you'd like
the changes to the metadata could be saved in a temp folder and the server could try re-compress the comic with replaced ComicInfo.xml in the background, and the archive file will be replaced after the compress is finished.

**Comment by Kussie** [comment] 2021-12-30 00:25
https://komga.org/guides/scan-analysis-refresh.html#book-metadata

The fields Komga uses from ComicInfo.xml are described in the documentation above.

**Comment by gotson** [comment] 2021-12-30 00:30
Duplicate of #82

**Closed by gotson** 2021-12-30 00:30 UTC
