### ISSUE TITLE
Add a list view mode to readlists

### ISSUE THREAD

**Issue by morsok** [gotson/komga#1044] opened 2023-01-12 23:06 UTC
### Describe your suggested feature

I'm creating a read list with 850+ books in it. I forgot to add one in the middle, it took me 5+ minutes to move it to where it should be.

If you offer a list view in addition to the current thumbnail view to read list, re-arranging would be much easier and faster.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2023-01-13 01:54
Duplicate of #743

**Closed by gotson** 2023-01-13 01:54 UTC
Labels: triage
