### ISSUE TITLE
url with port，ex： https://<domain>:<port>/opds/v1.2/catalog，but，inside href without port

### ISSUE THREAD

**Issue by ferocknew** [gotson/komga#1302] opened 2023-11-21 05:50 UTC
### Describe your suggested feature

url with port，ex： https://<domain>:<port>/opds/v1.2/catalog，but，inside href without port
please fix it

<img width="1117" alt="image" src="https://github.com/gotson/komga/assets/2178683/3fe90239-a355-4430-ac70-b9b1b3422486">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by ferocknew** [comment] 2023-11-21 06:00
old version opds url no this problem.


<img width="923" alt="image" src="https://github.com/gotson/komga/assets/2178683/78f3f243-2f09-420e-8ba5-f8573267a787">

**Comment by gotson** [comment] 2023-11-21 07:32
Looks like a duplicate of #1254

**Comment by ferocknew** [comment] 2023-11-21 08:02
ok，get it


<img width="529" alt="image" src="https://github.com/gotson/komga/assets/2178683/47beb4f1-e730-49e2-a8a3-d5455b801763">

**Closed** 2023-11-21 08:43 UTC
Labels: triage
