### ISSUE TITLE
Hope to optimize the double-page alignment function

### ISSUE THREAD

**Issue by hutao521** [gotson/komga#1397] opened 2024-01-17 12:53 UTC
### Hope to optimize the double-page alignment function

When reading comics in double-page mode, some contents that use two pages to display one scene will appear out of alignment due to the page order. Generally, I can change the page order by switching whether to display the cover, so that the comics are aligned. But when there are pictures with longer width in the comics, because this picture occupies a single page, switching whether to display the cover cannot adjust the page order.Wish there was a better way to adjust the order of the pages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2024-01-18 02:43
Duplicate of #803 it seems

**Closed by gotson** 2024-01-18 02:43 UTC
Labels: triage
