### ISSUE TITLE
Possibility of marking pages to be deleted in the reader

### ISSUE THREAD

**Issue by tomandocubatas** [gotson/komga#826] opened 2022-03-03 16:45 UTC
### Describe your suggested feature

Sometimes it is necessary to delete extra pages that the current process is not able to detect.
I think that a good option is that these could be marked from the reader.
For example including that functionality in the reader's toolbar.
That page to be deleted would end up being included in the duplicate pages functionality.

![imagen](https://user-images.githubusercontent.com/36165495/156610855-61b77f99-4f28-4e2e-96f7-f7b067b42932.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-03-04 01:20
Duplicate of #800

**Closed by gotson** 2022-03-04 01:20 UTC
Labels: enhancement
