### ISSUE TITLE
[Feature Request] enable iOS fullscreen

### ISSUE THREAD

**Issue by stonechitlin** [gotson/komga#565] opened 2021-07-01 06:30 UTC
### Is your feature request related to a problem? Please describe.
iOS allows websites that utilize the tag:
`<meta name=”apple-mobile-web-app-capable” content=”yes”>`
 To go full screen web browsing, making the viewing experience within komga even better.

### Describe the solution you'd like
I found this article that talks about the tag https://www.ispringsolutions.com/blog/how-to-make-a-website-full-screen-on-the-ipad

### Describe alternatives you've considered or other apps that can do what you want
I have tried several popular browsers on my iPad, none support full screen for some reason.

### Additional context
None

**Comment by gotson** [comment] 2021-07-02 03:52
Duplicate of https://github.com/gotson/komga/issues/227

**Comment by elit3ge** [comment] 2021-07-07 06:38
Will this work in Chrome as well?

**Comment by gotson** [comment] 2021-08-02 03:41
I had just added `mobile-web-app-capable` and `apple-mobile-web-app-capable`, tests on iPad and Android seems conclusive.

**Closed** 2021-08-02 03:40 UTC
Labels: enhancement

**Comment by stonechitlin** [comment] 2021-08-02 03:44
> I had just added `mobile-web-app-capable` and `apple-mobile-web-app-capable`, tests on iPad and Android seems conclusive.

Fantastic! Can't wait to try it out!

Thanks you for the continued work you put into this!

**Comment by gotson** [comment] 2021-08-02 03:46
> > I had just added `mobile-web-app-capable` and `apple-mobile-web-app-capable`, tests on iPad and Android seems conclusive.
> 
> Fantastic! Can't wait to try it out!
> 
> Thanks you for the continued work you put into this!

It took quite a long time, a similar issue made me find an iPad and have a look, that's where i found Apple handles [viewport badly](https://github.com/gotson/komga/issues/581#issuecomment-890679977). One way to fix it was to make it full screen, so here we are. Release coming up :)

**Comment by TheGreatestJannet** [comment] 2021-08-02 14:29
This doesn’t seem to work correctly on iPhones. After clicking login it opens an in app safari browser instead of just logging in. Pressing Done to close the in app browser brings you back to the login screen and signs you out.

**Comment by stonechitlin** [comment] 2021-08-02 14:32
Its working for me on an ipad, with komga open and logged in on the main "home screen" select the share button and then the "add to home screen" option. once navigating ios does give you an option to hit that done button and bring you back to the main bookmarked page if you drag down. Dragging back up will hide that option.

**Comment by TheGreatestJannet** [comment] 2021-08-02 14:38
Oh it works the same way on iPad too. I guess it wasn’t the full screen I expected as there is still the address bar that can’t be fully hidden.

**Comment by stonechitlin** [comment] 2021-08-02 14:41
the standard address bar is hidden, but only if you open it from a "add to homescreen" bookmark. there is a very small bar that just shows the url, but its not selectable/editable.

**Comment by stonechitlin** [comment] 2021-08-02 14:45
Just tested on my iphone, working there as well.

**Comment by TheGreatestJannet** [comment] 2021-08-02 16:18
But the login screen has no URL bar at all. Isn’t it meant to keep no URL bar after login too? Komga has back buttons already so there isn’t really a need for another one.

**Comment by stonechitlin** [comment] 2021-08-02 16:35
I'm not sure how else to explain it, I have taken some screen shots to show what you should see AFTER you have bookmarked komga by adding it to home screen using safari.  [https://photos.app.goo.gl/VC59WaJ1d5S838N98](url) Please note, this all done by using the new komga icon on your device. It is treated as a separate app.

**Comment by PhilippKammann** [comment] 2021-08-02 17:50
If I'm on the Komga Home/Dashboard page the adressbar is hidden (the same way as @stonechitlin screenshots show) but if I open any other page in Komga an address bar shows up ([Picture](https://imgur.com/a/eNTo6Yr)).

**Comment by stonechitlin** [comment] 2021-08-02 17:53
Yes I get that to, but if you scroll down it goes away. My so long as your not reading from down up it shouldn’t be an issue

**Comment by TheGreatestJannet** [comment] 2021-08-02 18:51
It goes away complete on devices without a home button. On older devices it stays there it just gets a bit smaller.

**Comment by tahngarth** [comment] 2021-08-11 15:48
Finally! /happydance
