### ISSUE TITLE
[Feature Request] Continuous scroll option

### ISSUE THREAD

**Issue by dead-line** [gotson/komga#144] opened 2020-04-23 12:13 UTC
### Is your feature request related to a problem? Please describe.

Not really. I've just gotten used to this way of viewing manga. So would be nice to have it here too.

### Describe the solution you'd like

When reading manga/comics, the next page is directly below the current page and the previous page is directly above, allowing one to scroll continuously to the top and bottom.

### Describe alternatives you've considered or other apps that can do what you want

Other apps include

- SumatraPDF
- Pico Viewer
- [mangareader](https://github.com/luejerry/html-mangareader)
- mangadex
- Acrobat reader
- Microsoft Word
 etc.

### Additional context
I can provide more details if needed.

Thank you for your hard work!

**Comment by gotson** [comment] 2020-04-23 12:14
Duplicate of #81

**Closed by gotson** 2020-04-23 12:14 UTC
