### ISSUE TITLE
[Feature Request] Give control over what libraries are used in the home screen

### ISSUE THREAD

**Issue by otravers** [gotson/komga#373] opened 2021-01-04 14:39 UTC
### Is your feature request related to a problem? Please describe.

All the sections on home - Keep Reading, On Deck, Recently Added/Updated Series - are currently built using all libraries. One might not want to feature all their libraries that way, depending on their content, purpose, frequency of updates etc.

### Describe the solution you'd like

Add the option to exclude any given library from the home screen, as Plex does on its advanced library settings:
![image](https://user-images.githubusercontent.com/3731532/103546134-49c00200-4e81-11eb-8eed-b9ae6876597b.png)

This would expand on https://github.com/gotson/komga/issues/131

**Comment by gotson** [comment] 2021-01-05 00:45
Duplicate of #229

**Closed by gotson** 2021-01-05 00:45 UTC
