### ISSUE TITLE
[Feature Request] Crop the white around the page in webui equivalent of "Crop borders" in Tachiyomi

### ISSUE THREAD

**Issue by April-ha** [gotson/komga#544] opened 2021-05-25 09:13 UTC
Hello
In the webui have the possibility to crop the white around the page.
The equivalent of "Crop borders" in Tachiyomi.
It is very useful on small screens.

thanks

**Comment by gotson** [comment] 2021-05-25 09:34
Duplicate of #126

**Closed** 2021-05-25 10:08 UTC
