### ISSUE TITLE
[Feature Request] Webtoon reading mode: Ability to turn on vertical spacing (margin) between comic's images

### ISSUE THREAD

**Issue by frykauf** [gotson/komga#538] opened 2021-05-15 15:27 UTC
I do love reading everything in webtoon mode (infinite scrolling), even manga.

But for manga I would like an option to **turn on** vertical margin between images.

And thank you for creating komga!

**Comment by gotson** [comment] 2021-05-15 23:35
Duplicate of #427

**Closed by gotson** 2021-05-15 23:35 UTC
