### ISSUE TITLE
Allow Custom "Libraries" Based On Filters

### ISSUE THREAD

**Issue by ASB2** [gotson/komga#979] opened 2022-09-23 16:52 UTC
### Describe your suggested feature

The ability to create custom Libraries that pull their contents based on a user defined rules. 

Example 
I want a collection of all batman comics I have in the server. I can setup a Custom Library called Batman with the rules (title contains "Batman" ) and (tags contain "batman").

This new Library would filter the Series already in Komga to display a list of all Series meeting these rules.

There should be an option for a custom Library to be created for a single user or for all users.

The intent of this is to allow better filtering of series to further divorce the file structure of comics from the way these comics are displayed in Komga.

Example Filters:
Total Page Count Of Series
Series Title
Any Chapter Title Contains
Tags
Chapter Count
Completion Status

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2022-09-23 23:51
Duplicate of #200

**Closed by gotson** 2022-09-23 23:51 UTC
Labels: triage
