### ISSUE TITLE
[Feature Request] Filter Option To Hide Series That Are In A Collection

### ISSUE THREAD

**Issue by HaydoZV2** [gotson/komga#389] opened 2021-01-20 06:45 UTC
### Is your feature request related to a problem? Please describe.
I like to keep a large portion of my library in specific collections once there are a few related series. In the browse view it would be nice to simplify by removing series that are in those collections as that's my preferred method of browsing those issues.

### Describe the solution you'd like
Adding a filter option to hide items that exist in at least one collection from the main Browse tab. 

### Describe alternatives you've considered or other apps that can do what you want
Plex libraries have an option to keep items that are in collections in the main library or hide them.

**Comment by gotson** [comment] 2021-01-20 07:11
Duplicate of #230

**Closed by gotson** 2021-01-20 07:11 UTC
