### ISSUE TITLE
[Bug] Book sorting over OPDS

### ISSUE THREAD

**Issue by Flyingfufu** [gotson/komga#118] opened 2020-03-21 15:49 UTC
### Komga environment
- **OS**: QNAP NAS Linux
- **Komga version**: v0.24.6
- [ ] **I am running Komga from the `jar`**
  - Java version: Java 8 installed
- [ ] **I have a problem in the web interface**
  - Browser (with version): Edge Chromium Canary and Chrome, both latest version
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): Chunky iOS
-

Hi,

Great job here, I really like it and slowly move on all my collection into KOMGA !

The issue is related to the book sorting while searching over OPDS in Chunky. 

Despite "opds: books are ordered by metadata.numberSort (60edbe1)" in v0.24.5, The Series do appears in Name descending order, but once in it, there is no way to sort by book Sort Number. All books appear in Name descending order only.

Best regards,

**Comment by Flyingfufu** [comment] 2020-03-21 15:54
Last version update didn't upload properly on my server... Fixed !

**Comment by gotson** [comment] 2020-03-22 10:37
can you provide the XML of your OPDS feed that shows the problem, along with the metadata of the books that are not sorted?

**Comment by Flyingfufu** [comment] 2020-03-22 11:05
Happy to do so, but can you please tell where to find this xml file ?

**Comment by gotson** [comment] 2020-03-22 11:15
You can explore the feed the same way chunky would, just navigate to the root url you put in chunky, if you're versed in xml it shouldn't be too much of a problem!

**Comment by Flyingfufu** [comment] 2020-03-22 11:31
Hi,

Here the 2 files. Txt can be renamed to xml and show one serie feed, and the picture show the same serie in Chunky. You can see the sorting order not being the same (correct in the xml, top to bottom). Last one is the view in the front end.

[2859.txt](https://github.com/gotson/komga/files/4365102/2859.txt)

<img width="1080" alt="Image PNG" src="https://user-images.githubusercontent.com/45739159/77248264-6e235880-6c38-11ea-95ae-9bea17f4f9eb.png">

![image](https://user-images.githubusercontent.com/45739159/77248318-cc503b80-6c38-11ea-9092-9d5b1b132e29.png)

Hope this helps.

**Comment by gotson** [comment] 2020-03-22 12:02
Could you provide the json from `/api/v1/series/2859/books` also?

**Comment by gotson** [comment] 2020-03-22 12:04
I noticed that the xml is properly ordered, so I guess it's a problem with Chunky that would sort by name.

Could you try to verify this hypothesis by changing the Title of a book and see if Chunky changes its sort?

**Comment by Flyingfufu** [comment] 2020-03-22 12:09
> Could you provide the json from `/api/v1/series/2859/books` also?

[2859 Json.txt](https://github.com/gotson/komga/files/4365178/2859.Json.txt)

**Comment by Flyingfufu** [comment] 2020-03-22 12:13
> I noticed that the xml is properly ordered, so I guess it's a problem with Chunky that would sort by name.
> 
> Could you try to verify this hypothesis by changing the Title of a book and see if Chunky changes its sort?

Here the result after changing only the title of the 1st book

<img width="1080" alt="Image PNG" src="https://user-images.githubusercontent.com/45739159/77249045-b776a680-6c3e-11ea-95db-02e75691e248.png">

**Comment by gotson** [comment] 2020-03-22 12:19
Unfortunately this is a client issues Chunky, as many OPDS clients, seem to not follow the specification.

**Comment by Flyingfufu** [comment] 2020-03-22 12:23
Right, was what I was wondering looking into the json and xml content. Will shot a mail to Chunky to see if they can fix it on their end.

Regards,

**Comment by gotson** [comment] 2020-03-22 12:28
Could you try with a series where books don't have names starting with numbers?

Just to confirm if Chunky always sorts by name, or if it tries to guess the order when there's numbers at the beginning.

**Comment by Flyingfufu** [comment] 2020-03-22 12:34
Same result... all sorted by names. I just sent a email to the Chunky support. Will keep you posted on their feedback.

**Comment by gotson** [comment] 2020-03-22 12:38
Thanks.

I'll close the issue in the meantime. If they come back with a proper answer and some explanations from the opds specification I would be happy to do something about it. 

I tried other opds clients and they were behave as expected though.

**Closed by gotson** 2020-03-22 12:38 UTC

**Comment by gotson** [comment] 2020-03-22 12:44
FYI the issue isn't new : https://ubooquity.userecho.com/communities/1/topics/44-sorting-order-issue-with-opds-feeds

**Comment by Flyingfufu** [comment] 2020-04-06 15:44
Just a short message to say thanks, as your 25.1 feature is what was needed to fix this issue.... You're a Master !

Best regards,

**Comment by gotson** [comment] 2020-04-07 01:11
Yes, sorry i forgot to come an post here, i remembered someone had the same issue but i forgot it was here, i thought i was a conversation on Discord 😅
