### ISSUE TITLE
[Feature Request] import Count from comicinfo.xml

### ISSUE THREAD

**Issue by Kiwi-13-plo** [gotson/komga#450] opened 2021-03-09 16:46 UTC
### Describe the solution you'd like
In ComicInfo.xml file, there is the number of the book but also a total number of books in the serie (Count)
It would be nice to have this information of count, agregate at the serie level.
This will show if we have all the serie books or not at first look.

To go further, if the field "count" is provided, so serie is considere like "ended", so the serie status should be fill by default.

**Comment by gotson** [comment] 2021-03-10 00:35
Duplicate of #298

**Comment by Kiwi-13-plo** [comment] 2021-03-10 18:17
> I would suggest using the most frequent value within all books of the series.
I am agree with this rule if the datas are not clean.

> I don't agree with that. There is no specification in Comicinfo.xml that mandate the count be present only for ended series. As such, count could be there for series in progress, or series in hiatus.
No problem, it depend how you handle your data. In some case the rule will be true but for others it would be wrong.

**Comment by GlassedSilver** [comment] 2021-03-22 08:39
> 
> 
> I was not aware of that `Count` attribute in Comicinfo.xml. There is no such field yet at series level to hold the total number of books in a series (#298).
> 
> > It would be nice to have this information of count, agregate at the serie level.
> 
> What should be the reducing function to compute the value at series level, if values at book level is not the same on all books?
> 
> I would suggest using the most frequent value within all books of the series.
> 
> > To go further, if the field "count" is provided, so serie is considere like "ended", so the serie status should be fill by default.
> 
> I don't agree with that. There is no specification in Comicinfo.xml that mandate the count be present only for ended series. As such, count could be there for series in progress, or series in hiatus.

I would throw an error at the user and make them look it up.
Usually manually looking something up beats badly guessing a book containing bogus data that the user may have missed, simply because you don't necessarily check these files once your metadata is filled already.

Maybe that's just me though?

**Comment by gotson** [comment] 2021-03-22 09:02
> > I was not aware of that `Count` attribute in Comicinfo.xml. There is no such field yet at series level to hold the total number of books in a series (#298).
> > > It would be nice to have this information of count, agregate at the serie level.
> > 
> > 
> > What should be the reducing function to compute the value at series level, if values at book level is not the same on all books?
> > I would suggest using the most frequent value within all books of the series.
> > > To go further, if the field "count" is provided, so serie is considere like "ended", so the serie status should be fill by default.
> > 
> > 
> > I don't agree with that. There is no specification in Comicinfo.xml that mandate the count be present only for ended series. As such, count could be there for series in progress, or series in hiatus.
> 
> I would throw an error at the user and make them look it up.
> Usually manually looking something up beats badly guessing a book containing bogus data that the user may have missed, simply because you don't necessarily check these files once your metadata is filled already.
> 
> Maybe that's just me though?

Can you clarify in what cases or for which reason you would throw an error?

**Comment by GlassedSilver** [comment] 2021-03-22 09:17
If the metadata is different on the count for example, then I would ask the user to manually set a value, because if a series gets dropped for example there's a possibly unexpected new count, but also it may be picked up again.

Maybe it got dropped in one region and still runs in the original region from which you may fill the rest, so you possibly end up with inconsistent metadata, making manual rework desirable.

**Comment by gotson** [comment] 2021-03-22 09:24
> If the metadata is different on the count for example, then I would ask the user to manually set a value, because if a series gets dropped for example there's a possibly unexpected new count, but also it may be picked up again.
> 
> Maybe it got dropped in one region and still runs in the original region from which you may fill the rest, so you possibly end up with inconsistent metadata, making manual rework desirable.

I'm sorry, maybe that's me not getting it, but I have no idea what you are talking about. What do you mean by "metadata is different on the count for example" ?

**Comment by GlassedSilver** [comment] 2021-03-22 09:34
> > It would be nice to have this information of count, agregate at the serie level.
> 
> What should be the reducing function to compute the value at series level, if values at book level is not the same on all books?
> 
> I would suggest using the most frequent value within all books of the series.
> 
> > To go further, if the field "count" is provided, so serie is considere like "ended", so the serie status should be fill by default.
> 
> I don't agree with that. There is no specification in Comicinfo.xml that mandate the count be present only for ended series. As such, count could be there for series in progress, or series in hiatus.

Talking about possibly inconsistency issues like these.
Could also apply to other metadata.

e.g.: genre: adventure in some books, others may list "action adventure" and another may have genres in another language.

In such a case for example we could manually map a genre tag to "translate it" into how our database calls that.
That would make "adv" and identifier to list "adventure" in the view in Komga. Just an idea.

**Comment by gotson** [comment] 2021-03-22 10:30
For each metadata field there is already a specific rule to aggregate multiple fields.

**Comment by GlassedSilver** [comment] 2021-03-22 11:51
I don't mean the general approach, I mean that inconsistency can indicate that manual resolving could be advisable. (user preference if they wanna be asked in such cases)

**Comment by MKH-42** [comment] 2021-05-14 22:08
For my understanding it would be a perfect solution to read the count from comicinfo.xml for all books in a series.
Than use the highest number. Reason: I often have a comicinfo.xml on an ongoing series. the older books has a lower count number.

The series should show you "8 books of 12" in your series.
Very fantastic could be to have a place holder for missing titles like it is in emby.

![grafik](https://user-images.githubusercontent.com/76835223/118336223-87105c80-b511-11eb-9405-238a259ed996.png)

What do you think? It this a good idea?
And yes, you can always change the count manually.

**Comment by gotson** [comment] 2021-05-15 00:00
Indeed using the highest number would probably be more appropriate.

**Closed** 2021-07-30 09:08 UTC
Labels: enhancement
