### ISSUE TITLE
[Bug] SQLStatement too long

### ISSUE THREAD

**Issue by SR-G** [gotson/komga#647] opened 2021-08-31 13:47 UTC
### Komga environment
- **OS**: Archlinux
- **Komga version**: 0.119-2
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug

Added a new library (with many, many files inside it).
Got this (technical / low level) error about one SQL statement being too long.

```
2021-08-31 13:42:14.182 ERROR 1 --- [ntContainer#1-1] o.g.komga.application.tasks.TaskHandler  : Task ScanLibrary(libraryId=063W2H47YBBZR) execution failed

org.jooq.exception.DataAccessException: SQL [select BOOK.ID, BOOK.CREATED_DATE, BOOK.LAST_MODIFIED_DATE, BOOK.FILE_LAST_MODIFIED, BOOK.NAME, BOOK.URL, BOOK.SERIES_ID, BOOK.FILE_SIZE, BOOK.NUMBER, BOOK.LIBRARY_ID, BOOK.FILE_HASH, BOOK.DELETED_DATE from BOOK where (BOOK.LIBRARY_ID = '063W2H47YBBZR' and BOOK.URL not in (<many many files>)]; [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
	at org.jooq_3.14.8.SQLITE.debug(Unknown Source) ~[na:na]
	at org.jooq.impl.Tools.translate(Tools.java:2903) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:333) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1555) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3941) ~[jooq-3.14.8.jar:na]
	at org.gotson.komga.infrastructure.jooq.BookDao.findAllByLibraryIdAndUrlNotIn(BookDao.kt:68) ~[classes/:na]
	at org.gotson.komga.infrastructure.jooq.BookDao$$FastClassBySpringCGLIB$$b9fe9944.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.gotson.komga.infrastructure.jooq.BookDao$$EnhancerBySpringCGLIB$$3113bb87.findAllByLibraryIdAndUrlNotIn(<generated>) ~[classes/:na]
	at org.gotson.komga.domain.service.LibraryContentLifecycle.scanRootFolder(LibraryContentLifecycle.kt:109) ~[classes/:na]
	at org.gotson.komga.application.tasks.TaskHandler.handleTask(TaskHandler.kt:49) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.8.jar:5.3.8]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.8.jar:5.3.8]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.8.jar:5.3.8]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
	at org.sqlite.core.DB.newSQLException(DB.java:1030) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.core.DB.newSQLException(DB.java:1042) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.core.DB.throwex(DB.java:1007) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.core.DB.prepare(DB.java:257) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar:na]
	at jdk.internal.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:238) ~[spring-jdbc-5.3.8.jar:5.3.8]
	at com.sun.proxy.$Proxy173.prepareStatement(Unknown Source) ~[na:na]
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:258) ~[jooq-3.14.8.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342) ~[jooq-3.14.8.jar:na]
	... 27 common frames omitted

```

**Comment by valdearg** [comment] 2021-08-31 14:00
Could you try the latest version of the docker image, you're on a slightly older version where this should already be resolved.

**Comment by gotson** [comment] 2021-08-31 14:01
Duplicate of #644 which has been fixed already

**Closed by gotson** 2021-08-31 14:01 UTC

**Comment by SR-G** [comment] 2021-08-31 14:06
Correct, docker image was ~ 24hours old, seems latest one is ok now.

```
docker pull gotson/komga
Using default tag: latest
latest: Pulling from gotson/komga
171857c49d0f: Already exists 
419640447d26: Already exists 
61e52f862619: Already exists 
dd4d4e9526b1: Already exists 
52d08c98b138: Already exists 
682c34070466: Pull complete 
e8928bbe7df3: Pull complete 
c75270980145: Pull complete 
22ed6096a406: Pull complete 
Digest: sha256:52cc66349025ccc032630202c2539922bb746101d080ff268f6f6ff95c9e78fa
Status: Downloaded newer image for gotson/komga:latest
docker.io/gotson/komga:latest
```
