### ISSUE TITLE
[Feature Request] Ability to set larger size for OPDS Thumbnails

### ISSUE THREAD

**Issue by howdy-im-david** [gotson/komga#1215] opened 2023-09-08 15:30 UTC
### Describe your suggested feature

Viewing comic covers in OPDS clients right now on high-resolution screens (i.e., iPad), is not a great experience as they're very blurry. Viewing the XML feed

```<link type="image/jpeg" rel="http://opds-spec.org/image/thumbnail" href="/opds/v1.2/books/{bookId}/thumbnail/small"/>```

the image size is 196x300 which is way too small. 

I would like to be able to define the thumbnail resize from based on % (100%-Original page size to whatever % size they're being resized to now.) This will allow the server owner to set a quality size appropriate for their environment and/or needs. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by howdy-im-david** [comment] 2023-09-08 15:42
Additionally, I see an open PR https://github.com/gotson/komga/pull/1031 for almost 8mo that may fix the problem, but no movement on it?

**Comment by gotson** [comment] 2023-09-09 00:11
Thumbnails are precomputed and stored. Increasing the size will increase the storage space and the data transfer size.

Duplicate of #861

**Closed by gotson** 2023-09-09 00:11 UTC
Labels: triage

**Comment by RickSWilliams** [comment] 2023-09-09 15:30
I know this just got closed, but I would really like this ability too. Even if buried in a config file. I’d be fine with the increased size.

**Comment by gotson** [comment] 2023-09-10 00:21
> I know this just got closed, but I would really like this ability too. Even if buried in a config file. I’d be fine with the increased size.

Follow #861 it's the same thing

**Comment by gotson** [comment] 2023-09-10 00:24
> Viewing comic covers in OPDS clients right now on high-resolution screens (i.e., iPad), is not a great experience as they're very blurry. Viewing the XML feed
> 
> `<link type="image/jpeg" rel="http://opds-spec.org/image/thumbnail" href="/opds/v1.2/books/{bookId}/thumbnail/small"/>`
> 
> the image size is 196x300 which is way too small.

There's 2 links, 1 for the small thumbnail, and 1 for the full size thumbnail.

If your opds client displays the small one in full screen, it's a client issue.

https://specs.opds.io/opds-1.2#522-artwork-relations

**Comment by TheHardew** [comment] 2023-09-17 12:30
@howdy-im-david I've updated the PR. You can build it yourself.
