### ISSUE TITLE
Last 2 pages not shown next to each other in double spread layout

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#1027] opened 2022-12-26 00:53 UTC
### Steps to reproduce

As mentioned in this issue, https://github.com/gotson/komga/issues/803

https://github.com/gotson/komga/blob/a1e9238bf5bca418f02b6daa14e6d9b4f4c5fb80/komga-webui/src/functions/book-spreads.ts#L16
By taking the last page, you can get into a double page situation like this:
E = Empty page
[last page, E]
which was taken from a spreads that looked like this:
[[1,2],[3, last page]]
Resulting in this little awkward situation:
[[1, 2], [3, E], [last page, E]

### Expected behavior

Empty pages shouldn't be shown in the middle of double pages.

### Actual behavior

Empty page is shown breaking up two pages that should be next to each other
![image](https://user-images.githubusercontent.com/32607317/209486703-6d221500-a336-45f0-9619-d20c44ae5657.png)
![image](https://user-images.githubusercontent.com/32607317/209486714-a651d6fc-a16c-4578-8ada-08dc0c384b07.png)

### Komga version

1.157.4

### Operating system

Windows 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment] 2023-01-01 12:58
so it's a duplicate of #803 ? why are you opening another issue ?

**Comment by kanjieater** [comment] 2023-01-04 19:29
It's a separate issue, as stated in both tickets. Im unclear which part makes this seem like it's the same issue besides that i mentioned it in that issue before creating a separate issue for it. Why do you think these are the same?

**Comment by gotson** [comment] 2023-01-05 04:31
What page layout are you using ?

**Comment by kanjieater** [comment] 2023-01-05 14:53
> What page layout are you using ?
"Double pages"

**Closed** 2023-01-06 02:46 UTC
Labels: troubleshooting

**Comment by kanjieater** [comment] 2023-01-06 21:21
Can we please reconsider this? It's a breaking assumption for the majority of cases as most digital comics dont have the back cover as the last page of a book.
In addition I cant find any other comic readers that do this. This is pretty unintuitive and a bad user experience for people that want to see the last two pages side by side like they were meant to be.
