### ISSUE TITLE
[Feature Request] Folder Mode

### ISSUE THREAD

**Issue by bmfrosty** [gotson/komga#732] opened 2021-11-23 05:26 UTC
### Is your feature request related to a problem? Please describe.
I have too many files that are unorganized over the course of several years.  I don't want to spend my time organizing them.  I'd like them to be navigable as a directory tree with a searchable index.

### Describe the solution you'd like
I'd like to be able to create a library where I give it a base folder (or folders) and komga presents it as a directory tree.  I'd also like for it to be searchable, and I'd love to be able to save searches and sort output by filename *or* path/filename.

### Describe alternatives you've considered or other apps that can do what you want
Nothing is doing quite what I want.

**Comment by gotson** [comment] 2021-11-23 05:56
Duplicate of #401

**Closed by gotson** 2021-11-23 05:56 UTC
