### ISSUE TITLE
[Bug] Download into zip instead original format

### ISSUE THREAD

**Issue by F4BB** [gotson/komga#744] opened 2021-12-10 10:24 UTC
### Komga environment
- **OS**: Mac os, Ipad OS
- **Komga version**: 0.135
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest from here : https://hub.docker.com/r/gotson/komga
- [ ] **I have a problem in the web interface**
  - Browser (with version): Chrome, Safari, Firefox (latest of all)

### Describe the bug

Each time i trie to download a CBZ files it's automaticly download into a zip file. i Try cbr, pdf, epub i have no probleme only the cbz file

### Steps to reproduce

1 i choose the comics
2 i clic the download buttom
3 automaticly download in .zip

### Expected behavior
Hope to have directly .cbz 

### Actual behavior
What happened instead.

### Additional context
i meet this probleme since i update into 0.135

### Log file
https://pastebin.com/ByNWASz0

I hope is enough it's my first github issue

**Comment by gotson** [comment] 2021-12-13 13:08
I tried on my macbook using Chrome, Safari, and Firefox, and cannot reproduce. Both Chrome and Firefox download a `.cbz`. Safari for some reason appends some numbers to the file name, but still saves it under `.cbz`.

On Android, using Chrome, it is saved as a `.cbz.zip` though.

Can you confirm whether you are getting a `.cbz.zip`, or just a `.zip` ? Could you also provide your MacOS version, and versions for all the browsers (so i can compare with mine) ?

My guess is that the browsers do not honor the `Content-Disposition` header, and instead overrides it with the content of the `Content-Type` header.

You can inspect the headers in the dev tool, you should see something like:

```
Content-Disposition: attachment; filename="file.cbz"
Content-Type: application/zip
```

**Comment by gotson** [comment] 2021-12-13 14:02
After more research, i found out that:
- it is totally fine, and even recommended, to provide both `Content-Disposition` and `Content-Type` response headers
- Android historically had (and apparently still has) trouble with `Content-Disposition` headers. The Android issue I encountered is hence a client problem, not a server problem.

**Comment by gotson** [comment] 2021-12-13 15:04
I've tested Firefox on Android, and it downloads a `cbz` as expected.

**Comment by F4BB** [comment] 2021-12-13 15:55
On mac os 

> I tried on my macbook using Chrome, Safari, and Firefox, and cannot reproduce. Both Chrome and Firefox download a `.cbz`. Safari for some reason appends some numbers to the file name, but still saves it under `.cbz`.
> 
> On Android, using Chrome, it is saved as a `.cbz.zip` though.
> 
> Can you confirm whether you are getting a `.cbz.zip`, or just a `.zip` ? Could you also provide your MacOS version, and versions for all the browsers (so i can compare with mine) ?
> 
> My guess is that the browsers do not honor the `Content-Disposition` header, and instead overrides it with the content of the `Content-Type` header.
> 
> You can inspect the headers in the dev tool, you should see something like:
> 
> ```
> Content-Disposition: attachment; filename="file.cbz"
> Content-Type: application/zip
> ```

On ios (ipad or iphone) i have .cbz.zip but on mac OS y have only .zip when i unzip i have my cbz

For the other response sorry but it's out of my skills, i just understand that not a Komga problem, i wait with the new ios update if it's the same "problem"

**Comment by gotson** [comment] 2021-12-14 02:08
I just tested on an iPhone:
- Safari does `.cbz.zip`
- Firefox does `.cbz`



> but on mac OS y have only .zip when i unzip i have my cbz

That is weird, can you state your MacOS version, and browser version?

**Comment by F4BB** [comment] 2021-12-14 14:57
I made the new ios update on iphone and ipad os and Mac OS Update everything is fine. i dont understand why but everything return to work like a charm

**Comment by gotson** [comment] 2021-12-15 00:57
> I made the new ios update on iphone and ipad os and Mac OS Update everything is fine. i dont understand why but everything return to work like a charm

I'll close this then.

**Closed by gotson** 2021-12-15 00:57 UTC
Labels: cannot reproduce, waiting for feedback
