### ISSUE TITLE
[Feature Request] Only show comic names in the library

### ISSUE THREAD

**Issue by fjjking** [gotson/komga#412] opened 2021-02-18 18:04 UTC
### Is your feature request related to a problem? Please describe.
I like to place comics by chapters in file,like is:
```
Comic name
    └── Vol. 1
             ├── 1.zip
             ├── 2.zip
             └── 3.zip
```
But there will be many volumes in the library,It's so messy.

### Describe the solution you'd like
Can we only show Comic name?Put them together?
If possible,it would be great.

### Describe alternatives you've considered or other apps that can do what you want
Like [Mango](https://github.com/hkalexling/Mango)

### Additional context
Like is:
![Comic name in library](https://user-images.githubusercontent.com/25077204/108400429-22b56800-7256-11eb-9c5e-a58d6d6054a5.png)
![Vol](https://user-images.githubusercontent.com/25077204/108400747-90619400-7256-11eb-99bf-b5934b424f3a.png)
![Chapter](https://user-images.githubusercontent.com/25077204/108400764-948db180-7256-11eb-9ddd-bc8b11225715.png)

**Comment by gotson** [comment] 2021-02-19 00:46
Duplicate of #46

Also please read the doc to understand how Komga works.

**Closed by gotson** 2021-02-19 00:46 UTC

**Comment by fjjking** [comment] 2021-02-19 01:40
ya,I've read the doc.
But why not support subfolders?
manga often has hundreds of chapters,it's messy in one folder.

**Comment by gotson** [comment] 2021-02-19 01:44
why would having 100 files in one folder be messy ? Folders are made for that. Komga works at metadata level, like Plex. If you want a file browser, use a file browser.

**Comment by fjjking** [comment] 2021-02-19 02:02
May be a habit?I like to place files by category
Anyway,I like komga's web read tool so mach.Thanks !

**Comment by gotson** [comment] 2021-02-19 02:24
You _can_ use any kind of directory structure with Komga, but that may require some rework. Come have a chat on Discord, the community will help you!
