### ISSUE TITLE
[Feature Request] Implementing Long Strip Web Reader

### ISSUE THREAD

**Issue by edwinbadillo** [gotson/komga#208] opened 2020-06-14 04:29 UTC
Current web reader supports both Single and Double page reading which works for most comics, manga, graphic novels etc.  It would be nice if there was mode that loads images as one consecutive long strip for media that is meant to be read as one long image.  The read progress API can be triggered using IntersectionObserver whenever the image is in the visible view port.

Example of long strip media (© NAVER WEBTOON CORP.):
https://www.webtoons.com/en/fantasy/tower-of-god/season-1-ep-1-1fheadons-floor/viewer?title_no=95&episode_no=2

Intersection Observer:
```
  const setReadObserver = (image) => {
    const observer = new IntersectionObserver(((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          // trigger read progress
        }
      });
    }));
    observer.observe(image);
  };
```

**Comment by gotson** [comment] 2020-06-14 04:43
Duplicate of #81

**Closed by gotson** 2020-06-14 04:43 UTC
