### ISSUE TITLE
Per library page view

### ISSUE THREAD

**Issue by Darkwolf1515** [gotson/komga#271] opened 2020-08-13 06:28 UTC
### Is your feature request related to a problem? Please describe.
Would like to be able to set my manga library to read right to left, and comics to read left to right without having to change it manually everytime. 

### Describe the solution you'd like
Just a toggle on the library to set how I want my pages to go 

### Describe alternatives you've considered or other apps that can do what you want
Cover on windows 10 is the top standard in cbz for me, it has this function by letting me pick manga mode per folder.

**Comment by gotson** [comment] 2020-08-13 06:30
Duplicate of #115

**Closed by gotson** 2020-08-13 06:30 UTC
